/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Arial Unicode MS32.c                                  *
* Font:        Arial Unicode MS                                      *
* Height:      32                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  32                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\zj\Desktop\ssss.txt                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontArialUnicodeMS32;

GUI_CONST_STORAGE unsigned char acGUI_FontArialUnicodeMS32_0055[ 160] = { /* code 0055, LATIN CAPITAL LETTER U */
    ________, _______X, ____XX__, ________, ________,
    ________, _______X, ____XX__, ________, ________,
    ________, ____XXXX, X___XX__, ________, ________,
    ________, ___XX___, __XXXXXX, ________, ________,
    ________, __XX____, XXXXXXXX, XX______, ________,
    ________, _XX____X, XX______, XXX_____, ________,
    ________, _X____XX, ________, __XX____, ________,
    ________, XX___XX_, ________, ___XX___, ________,
    ________, X___XX__, ________, ____XX__, ________,
    _______X, X___XX__, ________, ____XX__, ________,
    _______X, ___XX___, ________, _____XX_, ________,
    ______XX, ___XX___, ________, _____XX_, ________,
    ______X_, __XX____, ________, ______XX, ________,
    ______X_, __XX____, ________, ______XX, ________,
    _____XX_, __XX____, ________, ______XX, ________,
    _____X__, _XX_____, ________, _______X, X_______,
    ____XX__, _XX_____, ________, _______X, X_______,
    ____X___, _XX_____, ________, _______X, X_______,
    ____X___, XX______, ________, ________, XX______,
    ___XX___, XX______, ________, ________, XX______,
    ___X____, XX______, ________, ________, XX______,
    ___X___X, X_______, ________, ________, _XX_____,
    __XX___X, X_______, ________, ________, _XX_____,
    __XX___X, X_______, ________, ________, _XX_____,
    ______XX, X_______, ________, ________, _XXX____,
    ______XX, ________, ________, ________, __XX____,
    ______XX, ________, ________, ________, __XX____,
    ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
    ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
    ________, ________, _XXXXXXX, X_______, ________,
    ________, ________, __XXXXXX, ________, ________,
    ________, ________, ___XXXX_, ________, ________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontArialUnicodeMS32_CharInfo[3] = {
  {  40,  32,  5, acGUI_FontArialUnicodeMS32_0055 } /* code 0055 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontArialUnicodeMS32_Prop2 = {
   0x0055 /* first character */
  ,0x0055 /* last character  */
  ,&GUI_FontArialUnicodeMS32_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0  /* pointer to next GUI_FONT_PROP */
};


GUI_CONST_STORAGE GUI_FONT GUI_FontArialUnicodeMS32 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,32 /* height of font  */
  ,32 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,&GUI_FontArialUnicodeMS32_Prop2
};

