/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: x116y181
* Dimensions:  381 * 34
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsx116y181[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palx116y181 = {
  2,	/* number of entries */
  1, 	/* No transparency */
  &Colorsx116y181[0]
};

static GUI_CONST_STORAGE unsigned char acx116y181[] = {
  ________, ____XXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, _______X, XXXXXX__, ________, ________, ________, ________, ________, _____XXX, XXXX____, ________, 
        ________, ________, _XXXXXXX, X____XXX, XXXXXX__, ________, ________, ________, ________, ________, ________, _____XXX, XXXX___X, XXXXXX__, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ____XXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, X______X, XXXXXX__, ________, ________, ________, _______X, XXXXXX__, _____XXX, XXXX____, ________, 
        ________, ________, _XXXXXXX, X____XXX, XXXXX___, ________, ________, ________, ________, ________, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, ________, ________, ______XX, XXXXX___, ________, ________, ________, ________, ________,
  ________, ___XXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, X______X, XXXXXX__, ________, ________, ________, _______X, XXXXXX__, ____XXXX, XXX_____, ________, 
        ________, ________, _XXXXXXX, _____XXX, XXXXX___, ________, ________, ________, ________, ________, XXXXXXX_, _____XXX, XXXX__XX, XXXXX___, ________, ________, ______XX, XXXXX___, ________, ________, ________, ________, ________,
  ________, ___XXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, X______X, XXXXXX__, ________, ________, ________, _______X, XXXXXX__, ____XXXX, XXX_____, ________, 
        ________, ________, _XXXXXXX, ____XXXX, XXXX____, ________, ________, ________, ________, ________, XXXXXXX_, _____XXX, XXXX__XX, XXXXX___, ________, ________, ______XX, XXXXX___, ________, ________, ________, ________, ________,
  ________, ___XXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, _______X, XXXXX___, ________, ________, ________, ______XX, XXXXXX__, ____XXXX, XXX_____, ________, 
        ________, ________, _XXXXXXX, ____XXXX, XXXX____, ________, ________, ________, ________, _______X, XXXXXXX_, _____XXX, XXXX__XX, XXXXX___, ________, ________, _____XXX, XXXXX___, ________, ________, ________, ________, ________,
  ________, __XXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, _______X, XXXXX___, ________, ________, ________, ______XX, XXXXX___, ________, ________, ________, 
        ________, ________, _XXXXXXX, ____XXXX, XXXX____, ________, ________, ________, ________, _______X, XXXXXXX_, ________, ______XX, XXXXX___, ________, ________, _____XXX, XXXX____, ________, ________, ________, ________, ________,
  ________, __XXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, ______XX, XXXXX___, ________, ________, ________, ______XX, XXXXX___, ________, ________, ________, 
        ________, ________, _XXXXXXX, ____XXXX, XXX_____, ________, ________, ________, ________, _______X, XXXXXX__, ________, _____XXX, XXXX____, ________, ________, _____XXX, XXXX____, ________, ________, ________, ________, ________,
  ________, __XXXXXX, XXXXXXX_, ______XX, XXXX__XX, XXXX____, _______X, XXXXXXXX, ________, ___XXXXX, XXXX____, _______X, XXXXXXXX, ______XX, XXXXXXXX, XXXX__XX, XXXXX_XX, XXXXX___, _____XXX, XXXXXX__, ___XXXXX, XXXXXXXX, X__XXXXX, XX______, _XXXXXXX, 
        XX______, ________, _XXXXXXX, ___XXXXX, XXX_____, __XXXXXX, XXX_____, _XXXXXXX, _XXXXXX_, ____XXXX, XXXXXXXX, XX__XXXX, XXX__XXX, XXXX____, ___XXXXX, XXXX____, __XXXXXX, XXXXXXXX, ______XX, XXXXXXX_, _____XXX, XXXX_XXX, XXX_____,
  ________, _XXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXX___, _____XXX, XXXXXXXX, XX______, _XXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XX____XX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, X__XXXXX, XX_____X, XXXXXXXX, 
        XXXX____, ________, _XXXXXXX, ___XXXXX, XXX_____, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XX__XXXX, XXX__XXX, XXXX____, _XXXXXXX, XXXXXX__, __XXXXXX, XXXXXXXX, ____XXXX, XXXXXXXX, X____XXX, XXXXXXXX, XXXXX___,
  ________, _XXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXX__, __XXXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX, X__XXXXX, XX____XX, XXXXXXXX, 
        XXXXX___, ________, _XXXXXXX, ___XXXXX, XX_____X, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XX__XXXX, XXX__XXX, XXXX____, XXXXXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXX___,
  ________, XXXXXXX_, XXXXXXX_, ______XX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX, ___XXXXX, XX___XXX, XXXXXXXX, 
        XXXXX___, ________, XXXXXXXX, __XXXXXX, XX____XX, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXX___,
  ________, XXXXXXX_, XXXXXXX_, _____XXX, XXXXX__X, XXXXXX__, __XXXXXX, XX__XXXX, XXX____X, XXXXXX__, XXXXXXX_, ___XXXXX, XX__XXXX, XXX_____, _XXXXXX_, _____XXX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X____XXX, XXXX____, __XXXXXX, X____XXX, XXXX__XX, 
        XXXXX___, ________, XXXXXXXX, __XXXXXX, XX___XXX, XXXXX__X, XXXXXX__, XXXXXXXX, __XXXXXX, X_____XX, XXXXX___, ___XXXXX, XX__XXXX, XXX___XX, XXXXXX__, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, X__XXXXX, XX__XXXX, XXXX__XX, XXXXX___,
  ________, XXXXXX__, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, XXXXXXX_, __XXXXXX, X___XXXX, XXX_____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX___XX, 
        XXXXX___, ________, XXXXXXXX, __XXXXXX, XX___XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X_____XX, XXXXX___, ___XXXXX, XX__XXXX, XXX___XX, XXXXX___, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX___,
  _______X, XXXXXX__, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, XXXXXXX_, __XXXXXX, X___XXXX, XXX_____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX___XX, 
        XXXXX___, ________, XXXXXXX_, __XXXXXX, X____XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X_____XX, XXXXX___, ___XXXXX, XX__XXXX, XXX___XX, XXXXX___, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX___,
  _______X, XXXXXX__, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, _XXXXXXX, X___XXXX, XXX___XX, XXXXX___, XXXXXXX_, __XXXXXX, X___XXXX, XXX_____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX___XX, 
        XXXXX___, ________, XXXXXXX_, _XXXXXXX, X____XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X_____XX, XXXXX___, ___XXXXX, XX__XXXX, XXX__XXX, XXXXX___, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX___,
  _______X, XXXXX___, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, _XXXXXXX, ____XXXX, XXX___XX, XXXXX___, XXXXXXX_, _XXXXXXX, X__XXXXX, XXX_____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX___XX, 
        XXXXX___, ________, XXXXXXX_, _XXXXXXX, X____XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X_____XX, XXXXX___, ___XXXXX, XX__XXXX, XXX__XXX, XXXX____, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX___,
  ______XX, XXXXX___, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, _XXXXXXX, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, _XXXXXXX, X__XXXXX, XX_____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX___XXX, 
        XXXX____, ________, XXXXXXX_, _XXXXXXX, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, _____XXX, XXXX____, __XXXXXX, X__XXXXX, XX___XXX, XXXX___X, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX____,
  ______XX, XXXXX___, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, ________, __XXXXXX, XX___XXX, XXXX___X, XXXXXX__, _XXXXXXX, XX______, _______X, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX___XXX, 
        XXXX____, ________, XXXXXXX_, XXXXXXXX, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, _____XXX, XXXX____, __XXXXXX, X__XXXXX, XX______, ______XX, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX____,
  ______XX, XXXX____, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, ________, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXX__, __XXXXXX, XXXX____, _______X, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXXXX, XXXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX___XXX, 
        XXXX____, ________, XXXXXXX_, XXXXXXXX, ____XXXX, XXXXXXXX, XXXXX__X, XXXXXX__, _XXXXXXX, _____XXX, XXXX____, __XXXXXX, X__XXXXX, XX______, ____XXXX, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X__XXXXX, XX______, ________,
  _____XXX, XXXX____, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, ______XX, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXX__, __XXXXXX, XXXXXX__, _______X, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXXXX, XXXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX______, 
        ________, ________, XXXXXXX_, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXX__X, XXXXXX__, _XXXXXXX, _____XXX, XXXX____, __XXXXXX, X__XXXXX, XX______, __XXXXXX, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X__XXXXX, XX______, ________,
  _____XXX, XXXXXXXX, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, ____XXXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, _______X, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXXXX, XXXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX______, 
        ________, ________, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXX__X, XXXXXX__, _XXXXXXX, _____XXX, XXXX____, __XXXXXX, X__XXXXX, XX______, XXXXXXXX, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X__XXXXX, XX______, ________,
  _____XXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XX___XXX, XXXX____, __XXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, ______XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXXXXX, XXXXXXX_, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X_______, 
        ________, ________, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, XXXX__XX, XXXXX___, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, __XXXXXX, X_____XX, XXXXXXXX, XXXXX___, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, __XXXXXX, X_______, ________,
  ____XXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XX___XXX, XXXX____, _XXXXXXX, X_XXXXXX, X___XXXX, XXX_____, ________, _______X, XXXXXXXX, X_____XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXX___, ________, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X___XXXX, 
        XXX_____, ________, XXXXXXXX, XXXXXX__, ___XXXXX, XX______, ______XX, XXXXX___, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, __XXXXXX, X____XXX, XXXXX_XX, XXXXX___, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, __XXXXXX, X_______, ________,
  ____XXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XX___XXX, XXXX____, XXXXXXX_, __XXXXXX, X___XXXX, XXX_____, ________, ________, _XXXXXXX, X_____XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXX___, ________, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X___XXXX, 
        XXX_____, ________, XXXXXXXX, XXXXXX__, ___XXXXX, XX______, ______XX, XXXXX___, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, __XXXXXX, X_______, ________,
  ___XXXXX, XX______, XXXXXXX_, ___XXXXX, XX___XXX, XXXX____, XXXXXXX_, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, XXXXXXX_, _XXXXXXX, X_____XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X___XXXX, 
        XXX_____, _______X, XXXXXXXX, XXXXXX__, ___XXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, __XXXXXX, X_______, ________,
  ___XXXXX, XX______, XXXXXXX_, ___XXXXX, XX___XXX, XXXX____, XXXXXXX_, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, XXXXXXX_, _XXXXXXX, X_____XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X___XXXX, 
        XXX_____, _______X, XXXXXXXX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, __XXXXXX, X_______, ________,
  ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, _XXXXXXX, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, _XXXXXXX, _____XXX, XXXXX___, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, ___XXXXX, 
        XX______, _______X, XXXXXXXX, XXXXX___, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, _XXXXXXX, ___XXXXX, XX___XXX, XXXX____, _XXXXXXX, ______XX, XXXXX___, XXXXXXX_, _XXXXXXX, ________, ________,
  __XXXXXX, XX______, XXXXXXX_, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, _XXXXXXX, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, _XXXXXXX, _____XXX, XXXX____, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, ___XXXXX, 
        XX______, _______X, XXXXXXXX, XXXXX___, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, _XXXXXXX, ___XXXXX, XX___XXX, XXXX____, _XXXXXXX, ______XX, XXXXX___, XXXXXXX_, _XXXXXXX, ________, ________,
  __XXXXXX, X_______, XXXXXXX_, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, _XXXXXXX, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, _XXXXXXX, _____XXX, XXXX____, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, ___XXXXX, 
        XX______, _______X, XXXXXXXX, XXXX____, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, ___XXXXX, XXX_____, XXXXXXX_, _XXXXXXX, ___XXXXX, XX___XXX, XXXX____, _XXXXXXX, X_____XX, XXXXX___, XXXXXXX_, _XXXXXXX, ________, ________,
  __XXXXXX, X_______, XXXXXXX_, __XXXXXX, X___XXXX, XXX____X, XXXXXXX_, _XXXXXXX, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, XXXXXXXX, _____XXX, XXXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, __XXXXXX, XXXXX__X, XXXXXX__, _XXXXXXX, ___XXXXX, 
        XX______, _______X, XXXXXXXX, XXXX____, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, ___XXXXX, XXXXXX__, XXXXXXX_, _XXXXXXX, ___XXXXX, XX___XXX, XXXX____, _XXXXXXX, XXXX__XX, XXXXX___, XXXXXXX_, _XXXXXXX, ________, ________,
  _XXXXXXX, X_______, XXXXXXX_, __XXXXXX, X___XXXX, XXX____X, XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXXXXXX, XXXXX___, __XXXXXX, XXXXX__X, XXXXXX__, _XXXXXXX, XXXXXXXX, 
        X_______, _______X, XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XX___XXX, XXXX___X, XXXXXX__, ___XXXXX, XXXXXX__, XXXXXXX_, _XXXXXXX, ___XXXXX, XXXXXXXX, XXXX____, _XXXXXXX, XXXX__XX, XXXXXXXX, XXXXXX__, _XXXXXXX, ________, ________,
  _XXXXXXX, ________, XXXXXXX_, _XXXXXXX, ___XXXXX, XX_____X, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, _XXXXXXX, ___XXXXX, XX___XXX, XXXXXXXX, XXXXX___, __XXXXXX, XXXXX__X, XXXXX___, _XXXXXXX, XXXXXXXX, 
        X_______, _______X, XXXXXXXX, XXX_____, __XXXXXX, XXXXXXXX, XX__XXXX, XXX___XX, XXXXX___, ___XXXXX, XXXXX__X, XXXXXX__, XXXXXXX_, ___XXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XXXX__XX, XXXXXXXX, XXXXXX__, XXXXXXX_, ________, ________,
  _XXXXXXX, ________, XXXXXXX_, _XXXXXXX, ___XXXXX, XX_____X, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, X_______, XXXXXXXX, XXXXX___, _____XXX, XXXXXXX_, _XXXXXXX, ___XXXXX, XX____XX, XXXXXXXX, XXX_____, __XXXXXX, XXXX___X, XXXXX___, __XXXXXX, XXXXXXX_, 
        ________, _______X, XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX, ____XXXX, XXX___XX, XXXXX___, ___XXXXX, XXXXX__X, XXXXXX__, XXXXXXX_, ___XXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XXX____X, XXXXXXXX, XXXX____, XXXXXXX_, ________, ________,
  XXXXXXXX, ________, XXXXXXX_, _XXXXXXX, ___XXXXX, XX______, _XXXXXXX, _XXXXXX_, ______XX, XXXXXXX_, ________, __XXXXXX, XXX_____, ______XX, XXXXXXX_, _XXXXXXX, ___XXXXX, XX______, XXXXXXXX, X_______, ___XXXXX, XXXX___X, XXXXX___, ____XXXX, XXXXX___, 
        ________, _______X, XXXXXXXX, XXX_____, _____XXX, XXXXXX__, ____XXXX, XXX___XX, XXXXX___, ____XXXX, XXXXX__X, XXXXXX__, XXXXXXX_, _____XXX, XXXX_XXX, XXX_____, __XXXXXX, XXX_____, _XXXXXXX, XX______, XXXXXXX_, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmx116y181 = {
  381, /* XSize */
  34, /* YSize */
  48, /* BytesPerLine */
  1, /* BitsPerPixel */
  acx116y181,  /* Pointer to picture data (indices) */
  &Palx116y181  /* Pointer to palette */
};

/* *** End of file *** */
