/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: x182y170
* Dimensions:  399 * 34
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsx182y170[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palx182y170 = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsx182y170[0]
};

static GUI_CONST_STORAGE unsigned char acx182y170[] = {
  ________, ____XXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, X_______, ________, ________, ________, ________, ________, XXXXXXX_, ________, ________, ________, __XXXXXX, 
        XX_____X, XXXXXXX_, ____XXXX, XXX_____, ________, ________, ________, ________, __XXXXXX, X_______, ________, ________, ________, ________, ________, ________, ________, ________, ________, _____XXX, XXXX____, ________, ________, ________, 
        ________,
  ________, ____XXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXX____, __XXXXXX, X_______, ________, ________, ________, __XXXXXX, X_______, XXXXXXX_, ________, ________, ________, __XXXXXX, 
        XX_____X, XXXXXXX_, ____XXXX, XXX_____, ________, ________, ________, ________, __XXXXXX, X_______, ________, ________, ________, _____XXX, XXX_____, ________, ________, ________, XXXXXX__, _____XXX, XXXX____, ________, ________, ________, 
        ________,
  ________, ___XXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXX____, __XXXXXX, X_______, ________, ________, ________, __XXXXXX, X______X, XXXXXX__, ________, ________, ________, __XXXXXX, 
        XX_____X, XXXXXXX_, ____XXXX, XXX_____, ________, ________, ________, ________, __XXXXXX, X_______, ________, ________, ________, _____XXX, XXX_____, ________, ________, ________, XXXXXX__, ____XXXX, XXX_____, ________, ________, ________, 
        ________,
  ________, ___XXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, _____XXX, XXXX____, __XXXXXX, X_______, ________, ________, ________, __XXXXXX, X______X, XXXXXX__, ________, ________, ________, __XXXXXX, 
        XX____XX, XXXXXXX_, ___XXXXX, XX______, ________, ________, ________, ________, __XXXXXX, X_______, ________, ________, ________, ____XXXX, XXX_____, ________, ________, _______X, XXXXXX__, ____XXXX, XXX_____, ________, ________, ________, 
        ________,
  ________, ___XXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, _____XXX, XXX_____, __XXXXXX, ________, ________, ________, ________, _XXXXXXX, X______X, XXXXXX__, ________, ________, ________, __XXXXXX, 
        XX____XX, XXXXXXX_, ___XXXXX, XX______, ________, ________, ________, ________, __XXXXXX, X_______, ________, ________, ________, ____XXXX, XX______, ________, ________, _______X, XXXXX___, ____XXXX, XXX_____, ________, ________, ________, 
        ________,
  ________, __XXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, _____XXX, XXX_____, __XXXXXX, ________, ________, ________, ________, _XXXXXXX, ________, ________, ________, ________, ________, __XXXXXX, 
        XX____XX, XXXXXXX_, ___XXXXX, XX______, ________, ________, ________, ________, __XXXXXX, ________, ________, ________, ________, ____XXXX, XX______, ________, ________, _______X, XXXXX___, ________, ________, ________, ________, ________, 
        ________,
  ________, __XXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, _____XXX, XXX_____, _XXXXXXX, ________, ________, ________, ________, _XXXXXXX, ________, ________, ________, ________, ________, __XXXXXX, 
        XX____XX, XXXXXXX_, __XXXXXX, X_______, ________, ________, ________, ________, _XXXXXXX, ________, ________, ________, ________, ____XXXX, XX______, ________, ________, _______X, XXXXX___, ________, ________, ________, ________, ________, 
        ________,
  ________, __XXXXXX, XXXXXXX_, ______XX, XXXX__XX, XXXX____, ______XX, XXXXXXX_, ________, __XXXXXX, XXX_____, _XXXXXXX, XXXXXXX_, _XXXXXXX, _XXXXXXX, ________, XXXXXXXX, X_____XX, XXXXXXXX, XXXX__XX, XXXXX___, ____XXXX, XXXXX___, ________, __XXXXXX, 
        XX___XXX, XXXXXXX_, __XXXXXX, X______X, XXXXXXXX, ______XX, XXXXX_XX, XXXX____, _XXXXXXX, ___XXXXX, XXX_____, __XXXXXX, XXX_____, XXXXXXXX, XXXXXX__, ____XXXX, XXXXX___, ___XXXXX, XXXXXXXX, X__XXXXX, XX______, XXXXXXXX, X______X, XXXXX__X, 
        XXXXX___,
  ________, _XXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXX___, ____XXXX, XXXXXXXX, X_______, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXX__XX, XXXXX___, __XXXXXX, XXXXXXX_, ________, __XXXXXX, 
        XX___XXX, XXXXXXX_, __XXXXXX, X____XXX, XXXXXXXX, XX____XX, XXXXXXXX, XXXXXX__, _XXXXXXX, ___XXXXX, XX______, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXX__, __XXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, X__XXXXX, XX____XX, XXXXXXXX, XXX____X, XXXXXXXX, 
        XXXXXX__,
  ________, _XXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, XX_____X, XXXXXXXX, XXXXXX__, XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXXX__XX, XXXXX___, _XXXXXXX, XXXXXXXX, ________, __XXXXXX, 
        XX___XXX, XXXXXXX_, _XXXXXXX, ____XXXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXX__, _XXXXXXX, __XXXXXX, XX_____X, XXXXXXXX, XXXXXX__, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, X__XXXXX, XX___XXX, XXXXXXXX, XXXX___X, XXXXXXXX, 
        XXXXXXX_,
  ________, XXXXXXX_, XXXXXXX_, ______XX, XXXXXXXX, XXXXXX__, __XXXXXX, XXXXXXXX, XX____XX, XXXXXXXX, XXXXXX__, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXX___XX, XXXXX___, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, 
        XX__XXXX, XXXXXXX_, _XXXXXXX, ___XXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXX__, _XXXXXX_, __XXXXXX, X_____XX, XXXXXXXX, XXXXXX__, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, ___XXXXX, XX__XXXX, XXXXXXXX, XXXX___X, XXXXXXXX, 
        XXXXXXX_,
  ________, XXXXXXX_, XXXXXXX_, _____XXX, XXXXX__X, XXXXXX__, __XXXXXX, X__XXXXX, XX____XX, XXXXX__X, XXXXXX__, ____XXXX, XX______, XXXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX____, XXXXXXX_, _____XXX, XXXX____, XXXXXXX_, _XXXXXXX, ________, __XXXXXX, 
        XX__XXXX, XXXXXXX_, _XXXXXXX, ___XXXXX, X___XXXX, XXX__XXX, XXXXX__X, XXXXXX__, XXXXXXX_, _XXXXXXX, _____XXX, XXXXX__X, XXXXXX__, __XXXXXX, X______X, XXXXXXX_, _XXXXXXX, _____XXX, XXXX____, __XXXXXX, X___XXXX, XXX__XXX, XXXX__XX, XXXXXX__, 
        XXXXXXX_,
  ________, XXXXXX__, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, _XXXXXXX, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, _XXXXXXX, ________, __XXXXXX, 
        XX__XXXX, XXXXXXX_, XXXXXXX_, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXXX_, XXXXXXXX, _____XXX, XXXX___X, XXXXXX__, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, _____XXX, XXXX____, __XXXXXX, X__XXXXX, XX___XXX, XXXX__XX, XXXXX___, 
        XXXXXXX_,
  _______X, XXXXXX__, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, _XXXXXXX, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, _XXXXXXX, ________, __XXXXXX, 
        XX__XXXX, XXXXXXX_, XXXXXXX_, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXXX_, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, _____XXX, XXXX____, __XXXXXX, X__XXXXX, XX___XXX, XXXX__XX, XXXXX___, 
        XXXXXXX_,
  _______X, XXXXXX__, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, _XXXXXXX, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, _XXXXXXX, ________, __XXXXXX, 
        XX_XXXXX, XXXXXXX_, XXXXXXX_, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXXXX, XXXXXXX_, ____XXXX, XXXX___X, XXXXXX__, __XXXXXX, X_____XX, XXXXXX__, _XXXXXXX, _____XXX, XXXX____, __XXXXXX, X__XXXXX, XX___XXX, XXXX__XX, XXXXX___, 
        XXXXXXX_,
  _______X, XXXXX___, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, _XXXXXXX, ___XXXXX, XX__XXXX, XXXX__XX, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, _XXXXXXX, ________, __XXXXXX, 
        XX_XXXXX, XXXXXXXX, XXXXXX__, __XXXXXX, ____XXXX, XXX__XXX, XXXX___X, XXXXX___, XXXXXXXX, XXXXXX__, ____XXXX, XXXX___X, XXXXXX__, __XXXXXX, X_____XX, XXXXX___, _XXXXXXX, _____XXX, XXXX____, __XXXXXX, X__XXXXX, XX___XXX, XXXX__XX, XXXXX___, 
        XXXXXXX_,
  ______XX, XXXXX___, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, XXXXXXX_, __XXXXXX, X___XXXX, XXXX__XX, XXXXX___, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX___, XXXXXXX_, ________, __XXXXXX, 
        XX_XXXX_, XXXXXXXX, XXXXXX__, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX__X, XXXXXXXX, XXXXX___, ____XXXX, XXXX___X, XXXXX___, _XXXXXXX, ______XX, XXXXX___, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, 
        XXXXXX__,
  ______XX, XXXXX___, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, XXXXXXX_, __XXXXXX, X___XXXX, XXXXX___, ________, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX___, XXXXXXX_, ________, __XXXXXX, 
        XXXXXXX_, XXXXXXXX, XXXXXX__, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXX___X, XXXXXXXX, XXXXX___, ____XXXX, XXXXX___, ________, _XXXXXXX, ________, _______X, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, 
        XXXXXX__,
  ______XX, XXXX____, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, XXXXXXXX, XXXXXXXX, X____XXX, XXXXXXX_, ________, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, __XXXXXX, XXXXXXXX, XXX____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX___, XXXXXXX_, ________, __XXXXXX, 
        XXXXXXX_, XXXXXXXX, XXXXX___, _XXXXXXX, ___XXXXX, XX__XXXX, XXX_____, _______X, XXXXXXXX, XXXX____, _____XXX, XXXXXXX_, ________, _XXXXXXX, ________, _____XXX, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, 
        XXXXXX__,
  _____XXX, XXXX____, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, XXXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX, X_______, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, __XXXXXX, XXXXXXXX, XXX____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX___, ________, ________, __XXXXXX, 
        XXXXXXX_, XXXXXXXX, XXXXX___, _XXXXXXX, ___XXXXX, XX__XXXX, XXX_____, _______X, XXXXXXXX, XXXX____, _____XXX, XXXXXXXX, X_______, _XXXXXXX, ________, ___XXXXX, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, 
        XXXXXX__,
  _____XXX, XXXXXXXX, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, XXXXXXXX, XXXXXXXX, X______X, XXXXXXXX, XXX_____, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, __XXXXXX, XXXXXXXX, XXX____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX___, ________, ________, __XXXXXX, 
        XXXXXX__, XXXXXXXX, XXXXX___, _XXXXXX_, ___XXXXX, XX__XXXX, XXX_____, _______X, XXXXXXXX, XXXX____, _______X, XXXXXXXX, XXX_____, _XXXXXXX, ________, _XXXXXXX, XXXXXXX_, ____XXXX, XXX_____, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, 
        XXXXXX__,
  _____XXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XX___XXX, XXXX___X, XXXXXXXX, XXXXXXXX, ________, _XXXXXXX, XXX_____, _XXXXXXX, ______XX, XXXXX___, XXXXXXX_, _XXXXXXX, XXXXXXXX, XX____XX, XXXXX___, ___XXXXX, XX___XXX, XXXX____, ________, ________, __XXXXXX, 
        XXXXXX__, XXXXXXXX, XXXXX___, XXXXXXX_, __XXXXXX, X__XXXXX, XX______, ______XX, XXXXX_XX, XXXXX___, ________, _XXXXXXX, XXX_____, XXXXXXX_, _______X, XXXXXXXX, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, 
        XXXXX___,
  ____XXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, ________, ________, __XXXXXX, XXXX____, _XXXXXXX, ______XX, XXXXX___, XXXXXXX_, _XXXXXXX, ________, ______XX, XXXXX___, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, ________, __XXXXXX, 
        XXXXXX__, XXXXXXXX, XXXX____, XXXXXXX_, __XXXXXX, X__XXXXX, XX______, ______XX, XXXXX_XX, XXXXX___, ________, __XXXXXX, XXXX____, XXXXXXX_, ______XX, XXXXX__X, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, 
        XXXXX___,
  ____XXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, ________, ________, ____XXXX, XXXX____, _XXXXXXX, ______XX, XXXXX___, XXXXXXX_, _XXXXXXX, ________, ______XX, XXXXX___, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, ________, __XXXXXX, 
        XXXXX___, XXXXXXXX, XXXX____, XXXXXXX_, __XXXXXX, X__XXXXX, XX______, ______XX, XXXXX_XX, XXXXX___, ________, ____XXXX, XXXX____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, 
        XXXXX___,
  ___XXXXX, XX______, XXXXXXX_, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, _XXXXXXX, ___XXXXX, XX__XXXX, XXXX____, _XXXXXXX, ______XX, XXXXX___, XXXXXXX_, _XXXXXXX, ___XXXXX, XX____XX, XXXXX___, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, ________, __XXXXXX, 
        XXXXX___, XXXXXXXX, XXXX____, XXXXXXX_, __XXXXXX, X__XXXXX, XX______, ______XX, XXXXX_XX, XXXXX___, ___XXXXX, XX__XXXX, XXXX____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, 
        XXXXX___,
  ___XXXXX, XX______, XXXXXXX_, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, _XXXXXXX, ___XXXXX, XX__XXXX, XXXX____, _XXXXXXX, ______XX, XXXXX___, XXXXXXX_, _XXXXXXX, ___XXXXX, XX____XX, XXXXX___, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, ________, __XXXXXX, 
        XXXXX___, XXXXXXXX, XXX_____, XXXXXX__, __XXXXXX, X__XXXXX, XX______, ______XX, XXXXX__X, XXXXXX__, ___XXXXX, XX__XXXX, XXXX____, XXXXXXX_, _____XXX, XXX____X, XXXXXX__, ___XXXXX, XX______, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, 
        XXXXX___,
  ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, XXXXXXX_, __XXXXXX, X___XXXX, XXX_____, XXXXXXXX, _____XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, ________, __XXXXXX, 
        XXXXX___, XXXXXXXX, XXX____X, XXXXXX__, _XXXXXXX, __XXXXXX, X_______, _____XXX, XXXX___X, XXXXXX__, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, ____XXXX, XXX____X, XXXXX___, __XXXXXX, X______X, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, 
        XXXX____,
  __XXXXXX, XX______, XXXXXXX_, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, XXXXXXX_, __XXXXXX, X___XXXX, XXX_____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, ________, __XXXXXX, 
        XXXX____, XXXXXXXX, XXX____X, XXXXXX__, _XXXXXXX, __XXXXXX, X_______, _____XXX, XXXX___X, XXXXXX__, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX___, __XXXXXX, X______X, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, 
        XXXX____,
  __XXXXXX, X_______, XXXXXXX_, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, XXXXXXX_, __XXXXXX, X___XXXX, XXX_____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, ________, __XXXXXX, 
        XXXX____, XXXXXXXX, XX_____X, XXXXXX__, _XXXXXXX, __XXXXXX, X_______, _____XXX, XXXX___X, XXXXXXX_, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX___, __XXXXXX, X______X, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, 
        XXXX____,
  __XXXXXX, X_______, XXXXXXX_, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, XXXXXXX_, __XXXXXX, X__XXXXX, XXX_____, XXXXXXXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X____XXX, XXXXXXXX, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, ________, __XXXXXX, 
        XXXX____, XXXXXXXX, XX_____X, XXXXXX__, _XXXXXXX, __XXXXXX, X_______, _____XXX, XXXX____, XXXXXXX_, __XXXXXX, X__XXXXX, XXX____X, XXXXXXXX, XX__XXXX, XXXX__XX, XXXXX___, __XXXXXX, XXXXX__X, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, 
        XXXX____,
  _XXXXXXX, X_______, XXXXXXX_, __XXXXXX, X___XXXX, XXX___XX, XXXXXXXX, XXXXXX__, __XXXXXX, XXXXXXXX, XX______, XXXXXXXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, __XXXXXX, X___XXXX, XXXXXXXX, XXXX____, ________, __XXXXXX, 
        XXXX____, XXXXXXXX, XX_____X, XXXXXXXX, XXXXXXX_, __XXXXXX, X_______, _____XXX, XXXX____, XXXXXXX_, __XXXXXX, XXXXXXXX, XX_____X, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXX___, __XXXXXX, XXXXX__X, XXXXXX__, XXXXXXXX, XXXXXXXX, ___XXXXX, XX___XXX, 
        XXXX____,
  _XXXXXXX, ________, XXXXXXX_, _XXXXXXX, ___XXXXX, XX____XX, XXXXXXXX, XXXXXX__, __XXXXXX, XXXXXXXX, XX______, XXXXXXXX, XXX_XXXX, XXX___XX, XXXXX___, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, __XXXXXX, ____XXXX, XXXXXXXX, XXXX____, ________, __XXXXXX, 
        XXX_____, XXXXXXXX, X______X, XXXXXXXX, XXXXXXX_, _XXXXXXX, ________, ____XXXX, XXX_____, XXXXXXX_, __XXXXXX, XXXXXXXX, XX_____X, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXX____, __XXXXXX, XXXXX_XX, XXXXX___, XXXXXXXX, XXXXXXXX, __XXXXXX, X___XXXX, 
        XXX_____,
  _XXXXXXX, ________, XXXXXXX_, _XXXXXXX, ___XXXXX, XX_____X, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, ________, XXXXXXXX, XX__XXXX, XXX___XX, XXXXX___, _XXXXXXX, XXXXXX__, _____XXX, XXXXXXX_, __XXXXXX, _____XXX, XXXXXXXX, XX______, ________, __XXXXXX, 
        XXX_____, XXXXXXXX, X_______, XXXXXXXX, XXXXX___, _XXXXXXX, ________, ____XXXX, XXX_____, XXXXXXXX, ___XXXXX, XXXXXXXX, ________, XXXXXXXX, X___XXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXX__XX, XXXXX___, _XXXXXXX, XXXXXX__, __XXXXXX, X___XXXX, 
        XXX_____,
  XXXXXXXX, ________, XXXXXXX_, _XXXXXXX, ___XXXXX, XX______, _XXXXXXX, XX______, _____XXX, XXXXXX__, ________, _XXXXXXX, XX__XXXX, XXX___XX, XXXXX___, ___XXXXX, XXXX____, ______XX, XXXXXXX_, __XXXXXX, _______X, XXXXXXXX, ________, ________, __XXXXXX, 
        XXX_____, XXXXXXXX, X_______, __XXXXXX, XXX_____, _XXXXXXX, ________, ____XXXX, XXX_____, _XXXXXXX, _____XXX, XXXXXX__, ________, _XXXXXXX, X_____XX, XXXXX_XX, XXXX____, ____XXXX, XXXX__XX, XXXXX___, ___XXXXX, XXXX____, __XXXXXX, X___XXXX, 
        XXX_____
};

GUI_CONST_STORAGE GUI_BITMAP bmx182y170 = {
  399, /* XSize */
  34, /* YSize */
  50, /* BytesPerLine */
  1, /* BitsPerPixel */
  acx182y170,  /* Pointer to picture data (indices) */
  &Palx182y170  /* Pointer to palette */
};

/* *** End of file *** */
