/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: x191y249
* Dimensions:  420 * 34
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsx191y249[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palx191y249 = {
  2,	/* number of entries */
  1, 	/* No transparency */
  &Colorsx191y249[0]
};

static GUI_CONST_STORAGE unsigned char acx191y249[] = {
  ________, ____XXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, _______X, XXXXXX__, ________, ________, ________, ________, ________, _____XXX, XXXX____, ________, 
        ________, _______X, XXXXXXX_, ____XXXX, XXXX____, _XXXXXXX, ________, ________, ________, ________, _______X, XXXXXX__, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, X_______, 
        ________, ________, ________, ________,
  ________, ____XXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, X______X, XXXXXX__, ________, ________, ________, _______X, XXXXXX__, _____XXX, XXXX____, ________, 
        ________, _______X, XXXXXXX_, ____XXXX, XXXX____, _XXXXXXX, ________, ________, ________, ________, _______X, XXXXXX__, ________, ________, ________, ________, _XXXXXXX, ________, ________, ________, _____XXX, XXX_____, __XXXXXX, X_______, 
        ________, ________, ________, ________,
  ________, ___XXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, X______X, XXXXXX__, ________, ________, ________, _______X, XXXXXX__, ____XXXX, XXX_____, ________, 
        ________, _______X, XXXXXXX_, ____XXXX, XXXX____, _XXXXXXX, ________, ________, ________, ________, _______X, XXXXXX__, ________, ________, ________, ________, _XXXXXXX, ________, ________, ________, _____XXX, XXX_____, _XXXXXXX, ________, 
        ________, ________, ________, ________,
  ________, ___XXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, X______X, XXXXXX__, ________, ________, ________, _______X, XXXXXX__, ____XXXX, XXX_____, ________, 
        ________, _______X, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXX_, ________, ________, ________, ________, _______X, XXXXXX__, ________, ________, ________, ________, _XXXXXXX, ________, ________, ________, ____XXXX, XXX_____, _XXXXXXX, ________, 
        ________, ________, ________, ________,
  ________, ___XXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, _______X, XXXXX___, ________, ________, ________, ______XX, XXXXXX__, ____XXXX, XXX_____, ________, 
        ________, _______X, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXX_, ________, ________, ________, ________, _______X, XXXXXX__, ________, ________, ________, ________, XXXXXXXX, ________, ________, ________, ____XXXX, XX______, _XXXXXXX, ________, 
        ________, ________, ________, ________,
  ________, __XXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, _______X, XXXXX___, ________, ________, ________, ______XX, XXXXX___, ________, ________, ________, 
        ________, _______X, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXX_, ________, ________, ________, ________, _______X, XXXXX___, ________, ________, ________, ________, XXXXXXXX, ________, ________, ________, ____XXXX, XX______, ________, ________, 
        ________, ________, ________, ________,
  ________, __XXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, ______XX, XXXXX___, ________, ________, ________, ______XX, XXXXX___, ________, ________, ________, 
        ________, _______X, XXXXXXX_, ___XXXXX, XXXX___X, XXXXXX__, ________, ________, ________, ________, ______XX, XXXXX___, ________, ________, ________, ________, XXXXXXX_, ________, ________, ________, ____XXXX, XX______, ________, ________, 
        ________, ________, ________, ________,
  ________, __XXXXXX, XXXXXXX_, ______XX, XXXX__XX, XXXX____, _______X, XXXXXXXX, ________, ___XXXXX, XXXX____, _______X, XXXXXXXX, ______XX, XXXXXXXX, XXXX__XX, XXXXX_XX, XXXXX___, _____XXX, XXXXXX__, ___XXXXX, XXXXXXXX, X__XXXXX, XX______, _XXXXXXX, 
        XX______, _______X, XXXXXXX_, __XXXXXX, XXXX___X, XXXXXX__, ____XXXX, XXXXX___, ___XXXXX, XX_XXXXX, X_____XX, XXXXX___, XXXXXXXX, _______X, XXXXXXXX, _____XXX, XXXXXXXX, XXX_____, _XXXXXXX, XX______, XXXXXXXX, XXXXXX__, XXXXXXX_, _____XXX, 
        XXXXXX__, ____XXXX, XX__XXXX, XX______,
  ________, _XXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXX___, _____XXX, XXXXXXXX, XX______, _XXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XX____XX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, X__XXXXX, XX_____X, XXXXXXXX, 
        XXXX____, _______X, XXXXXXX_, __XXXXXX, XXXX___X, XXXXXX__, __XXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, XXX___XX, XXXXX___, XXXXXXX_, _____XXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXX____X, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXX__, XXXXXXX_, ___XXXXX, 
        XXXXXXXX, ____XXXX, XXXXXXXX, XXX_____,
  ________, _XXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXX__, __XXXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX, X__XXXXX, XX____XX, XXXXXXXX, 
        XXXXX___, _______X, XXXXXXX_, __XXXXXX, XXXX__XX, XXXXX___, _XXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, XXX___XX, XXXXX__X, XXXXXXX_, ____XXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXX__, XXXXXXX_, __XXXXXX, 
        XXXXXXXX, X___XXXX, XXXXXXXX, XXXX____,
  ________, XXXXXXX_, XXXXXXX_, ______XX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX, ___XXXXX, XX___XXX, XXXXXXXX, 
        XXXXX___, _______X, XXXXXXX_, _XXXXXXX, XXXX__XX, XXXXX___, XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, XXX___XX, XXXX___X, XXXXXX__, ___XXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXX___, XXXXXXX_, _XXXXXXX, 
        XXXXXXXX, X___XXXX, XXXXXXXX, XXXX____,
  ________, XXXXXXX_, XXXXXXX_, _____XXX, XXXXX__X, XXXXXX__, __XXXXXX, XX__XXXX, XXX____X, XXXXXX__, XXXXXXX_, ___XXXXX, XX__XXXX, XXX_____, _XXXXXX_, _____XXX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X____XXX, XXXX____, __XXXXXX, X____XXX, XXXX__XX, 
        XXXXX___, _______X, XXXXXXX_, _XXXXXXX, XXXX__XX, XXXXX___, XXXXXX__, _XXXXXXX, __XXXXXX, XX__XXXX, XXX__XXX, XXXX__XX, XXXXX___, __XXXXXX, XX__XXXX, XXX____X, XXXXXX__, ____XXXX, XXXX__XX, XXXXX___, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, 
        __XXXXXX, X__XXXXX, XXX__XXX, XXXX____,
  ________, XXXXXX__, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, XXXXXXX_, __XXXXXX, X___XXXX, XXX_____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX___XX, 
        XXXXX___, _______X, XXXXXXX_, _XXXXXXX, XXXX_XXX, XXXX___X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX_XXX, XXXXX___, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX___, __XXXXXX, X______X, XXXXXX__, XXXXXXX_, 
        __XXXXXX, X__XXXXX, XX___XXX, XXXX____,
  _______X, XXXXXX__, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, XXXXXXX_, __XXXXXX, X___XXXX, XXX_____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX___XX, 
        XXXXX___, _______X, XXXXXXX_, _XXXXXXX, XXXX_XXX, XXXX___X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX_XXX, XXXX____, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX___, __XXXXXX, X______X, XXXXXX__, XXXXXXX_, 
        __XXXXXX, X__XXXXX, XX___XXX, XXXX____,
  _______X, XXXXXX__, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, _XXXXXXX, X___XXXX, XXX___XX, XXXXX___, XXXXXXX_, __XXXXXX, X___XXXX, XXX_____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX___XX, 
        XXXXX___, _______X, XXXXXXX_, XXXXXXXX, XXXX_XXX, XXXX___X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXXXXXX, XXXX____, _XXXXXXX, X___XXXX, XXX____X, XXXXXX__, ___XXXXX, XXX___XX, XXXXX___, __XXXXXX, X______X, XXXXXX__, XXXXXXX_, 
        __XXXXXX, X__XXXXX, XX___XXX, XXXX____,
  _______X, XXXXX___, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, _XXXXXXX, ____XXXX, XXX___XX, XXXXX___, XXXXXXX_, _XXXXXXX, X__XXXXX, XXX_____, XXXXXXX_, _____XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX___XX, 
        XXXXX___, _______X, XXXXXXX_, XXXXXXXX, XXXXXXXX, XXX____X, XXXXX___, _XXXXXXX, __XXXXXX, X___XXXX, XX___XXX, XXXXXXXX, XXX_____, _XXXXXXX, X___XXXX, XXX____X, XXXXXX__, ___XXXXX, XX____XX, XXXXX___, __XXXXXX, X______X, XXXXXX__, XXXXXXX_, 
        __XXXXXX, X__XXXXX, XX___XXX, XXXX____,
  ______XX, XXXXX___, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, _XXXXXXX, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, _XXXXXXX, X__XXXXX, XX_____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX___XXX, 
        XXXX____, _______X, XXXXXXX_, XXXX_XXX, XXXXXXXX, XXX___XX, XXXXX___, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXXXXXXX, XX______, _XXXXXXX, X___XXXX, XX____XX, XXXXX___, ___XXXXX, XX___XXX, XXXX____, _XXXXXXX, ______XX, XXXXX__X, XXXXXX__, 
        _XXXXXXX, __XXXXXX, X___XXXX, XXX_____,
  ______XX, XXXXX___, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, ________, __XXXXXX, XX___XXX, XXXX___X, XXXXXX__, _XXXXXXX, XX______, _______X, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX___XXX, 
        XXXX____, _______X, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXX___XX, XXXXX___, XXXXXXX_, _XXXXXXX, ___XXXXX, X___XXXX, XXXXXXXX, XX______, _XXXXXXX, XX______, ______XX, XXXXX___, ________, ____XXXX, XXXX____, _XXXXXXX, ______XX, XXXXX__X, XXXXXX__, 
        _XXXXXXX, __XXXXXX, X___XXXX, XXX_____,
  ______XX, XXXX____, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, ________, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXX__, __XXXXXX, XXXX____, _______X, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXXXX, XXXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX___XXX, 
        XXXX____, _______X, XXXXXXXX, XXXX_XXX, XXXXXXXX, XX____XX, XXXXX___, XXXXXXX_, _XXXXXXX, ________, ____XXXX, XXXXXXXX, X_______, __XXXXXX, XXXX____, ______XX, XXXXX___, ________, __XXXXXX, XXXX____, _XXXXXXX, ______XX, XXXXX__X, XXXXXX__, 
        _XXXXXXX, __XXXXXX, X___XXXX, XXX_____,
  _____XXX, XXXX____, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, ______XX, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXX__, __XXXXXX, XXXXXX__, _______X, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXXXX, XXXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX______, 
        ________, _______X, XXXXXXXX, XXXX_XXX, XXXXXXXX, XX____XX, XXXXX___, XXXXXXX_, _XXXXXXX, ________, ____XXXX, XXXXXXXX, X_______, __XXXXXX, XXXXXX__, ______XX, XXXXX___, ________, XXXXXXXX, XXXX____, _XXXXXXX, ______XX, XXXXX__X, XXXXXX__, 
        _XXXXXXX, __XXXXXX, X___XXXX, XXX_____,
  _____XXX, XXXXXXXX, XXXXXXX_, ____XXXX, XXX___XX, XXXXX___, ____XXXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, _______X, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXXXX, XXXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX______, 
        ________, _______X, XXXXXXXX, XXX__XXX, XXXXXXXX, XX____XX, XXXX____, XXXXXXX_, _XXXXXXX, ________, ____XXXX, XXXXXXXX, X_______, ____XXXX, XXXXXXXX, ______XX, XXXXX___, ______XX, XXXXXXXX, XXXX____, _XXXXXXX, ______XX, XXXXX__X, XXXXXX__, 
        _XXXXXXX, __XXXXXX, X___XXXX, XXX_____,
  _____XXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XX___XXX, XXXX____, __XXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, ______XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXXXXX, XXXXXXX_, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X_______, 
        ________, _______X, XXXXXXXX, XXX__XXX, XXXXXXXX, XX___XXX, XXXX___X, XXXXXX__, XXXXXXX_, ________, ___XXXXX, XX_XXXXX, XX______, ______XX, XXXXXXXX, _____XXX, XXXX____, ____XXXX, XXXXXXXX, XXX_____, XXXXXXX_, _____XXX, XXXX__XX, XXXXX___, 
        XXXXXXX_, _XXXXXXX, ___XXXXX, XX______,
  ____XXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XX___XXX, XXXX____, _XXXXXXX, X_XXXXXX, X___XXXX, XXX_____, ________, _______X, XXXXXXXX, X_____XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXX___, ________, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X___XXXX, 
        XXX_____, _______X, XXXXXXXX, XXX__XXX, XXXXXXXX, X____XXX, XXXX___X, XXXXXX__, XXXXXXX_, ________, ___XXXXX, XX_XXXXX, XX______, _______X, XXXXXXXX, X____XXX, XXXX____, ___XXXXX, XXX_XXXX, XXX_____, XXXXXXX_, _____XXX, XXXX__XX, XXXXX___, 
        XXXXXXX_, _XXXXXXX, ___XXXXX, XX______,
  ____XXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XX___XXX, XXXX____, XXXXXXX_, __XXXXXX, X___XXXX, XXX_____, ________, ________, _XXXXXXX, X_____XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXX___, ________, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X___XXXX, 
        XXX_____, _______X, XXXXXXXX, XX___XXX, XXXXXXXX, X____XXX, XXXX___X, XXXXXX__, XXXXXXX_, ________, ___XXXXX, XX_XXXXX, XX______, ________, _XXXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX_____, XXXXXXX_, _____XXX, XXXX__XX, XXXXX___, 
        XXXXXXX_, _XXXXXXX, ___XXXXX, XX______,
  ___XXXXX, XX______, XXXXXXX_, ___XXXXX, XX___XXX, XXXX____, XXXXXXX_, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, XXXXXXX_, _XXXXXXX, X_____XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X___XXXX, 
        XXX_____, _______X, XXXXXXXX, XX___XXX, XXXXXXXX, X____XXX, XXXX___X, XXXXXX__, XXXXXXX_, ________, ___XXXXX, XX_XXXXX, XX______, XXXXXXX_, _XXXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX_____, XXXXXXX_, _____XXX, XXXX__XX, XXXXX___, 
        XXXXXXX_, _XXXXXXX, ___XXXXX, XX______,
  ___XXXXX, XX______, XXXXXXX_, ___XXXXX, XX___XXX, XXXX____, XXXXXXX_, __XXXXXX, X___XXXX, XXX___XX, XXXXX___, XXXXXXX_, _XXXXXXX, X_____XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X___XXXX, 
        XXX_____, _______X, XXXXXXXX, XX___XXX, XXXXXXXX, _____XXX, XXX____X, XXXXXX__, XXXXXXX_, ________, ___XXXXX, XX__XXXX, XXX_____, XXXXXXX_, _XXXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX_____, XXXXXXX_, _____XXX, XXXX__XX, XXXXX___, 
        XXXXXXX_, _XXXXXXX, ___XXXXX, XX______,
  ___XXXXX, XX______, XXXXXXX_, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, _XXXXXXX, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, _XXXXXXX, _____XXX, XXXXX___, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, ___XXXXX, 
        XX______, _______X, XXXXXXXX, XX___XXX, XXXXXXXX, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, ________, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, _XXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX_____X, XXXXXX__, ____XXXX, XXX__XXX, XXXX___X, 
        XXXXXX__, XXXXXXX_, __XXXXXX, X_______,
  __XXXXXX, XX______, XXXXXXX_, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, _XXXXXXX, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, _XXXXXXX, _____XXX, XXXX____, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, ___XXXXX, 
        XX______, _______X, XXXXXXXX, X____XXX, XXXXXXXX, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, ________, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, _XXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX_____X, XXXXXX__, ____XXXX, XXX__XXX, XXXX___X, 
        XXXXXX__, XXXXXXX_, __XXXXXX, X_______,
  __XXXXXX, X_______, XXXXXXX_, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, _XXXXXXX, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, _XXXXXXX, _____XXX, XXXX____, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, __XXXXXX, X______X, XXXXXX__, _XXXXXXX, ___XXXXX, 
        XX______, _______X, XXXXXXXX, X____XXX, XXXXXXX_, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, ________, __XXXXXX, X___XXXX, XXXX___X, XXXXXX__, _XXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX_____X, XXXXXX__, ____XXXX, XXX__XXX, XXXX___X, 
        XXXXXX__, XXXXXXX_, __XXXXXX, X_______,
  __XXXXXX, X_______, XXXXXXX_, __XXXXXX, X___XXXX, XXX____X, XXXXXXX_, _XXXXXXX, ___XXXXX, XX___XXX, XXXX___X, XXXXXX__, XXXXXXXX, _____XXX, XXXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, __XXXXXX, XXXXX__X, XXXXXX__, _XXXXXXX, ___XXXXX, 
        XX______, _______X, XXXXXXXX, X____XXX, XXXXXXX_, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, ________, __XXXXXX, X____XXX, XXXX___X, XXXXXX__, XXXXXXXX, ____XXXX, XXXXXXX_, _XXXXXXX, X__XXXXX, XX_____X, XXXXXXXX, XX__XXXX, XXX__XXX, XXXX___X, 
        XXXXXX__, XXXXXXX_, __XXXXXX, X_______,
  _XXXXXXX, X_______, XXXXXXX_, __XXXXXX, X___XXXX, XXX____X, XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXXXXXX, XXXXX___, __XXXXXX, XXXXX__X, XXXXXX__, _XXXXXXX, XXXXXXXX, 
        X_______, _______X, XXXXXXXX, X____XXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXX___X, XXXXXX__, ________, __XXXXXX, X____XXX, XXXX___X, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX, XX_____X, XXXXXXXX, XX__XXXX, XXX__XXX, XXXXXXXX, 
        XXXXX___, XXXXXXX_, __XXXXXX, X_______,
  _XXXXXXX, ________, XXXXXXX_, _XXXXXXX, ___XXXXX, XX_____X, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, _XXXXXXX, ___XXXXX, XX___XXX, XXXXXXXX, XXXXX___, __XXXXXX, XXXXX__X, XXXXX___, _XXXXXXX, XXXXXXXX, 
        X_______, _______X, XXXXXXXX, _____XXX, XXXXXX__, ____XXXX, XXXXXXXX, XXXX__XX, XXXXX___, ________, _XXXXXXX, _____XXX, XXXX___X, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX, X______X, XXXXXXXX, XX_XXXXX, XX___XXX, XXXXXXXX, 
        XXXXX__X, XXXXXX__, _XXXXXXX, ________,
  _XXXXXXX, ________, XXXXXXX_, _XXXXXXX, ___XXXXX, XX_____X, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, X_______, XXXXXXXX, XXXXX___, _____XXX, XXXXXXX_, _XXXXXXX, ___XXXXX, XX____XX, XXXXXXXX, XXX_____, __XXXXXX, XXXX___X, XXXXX___, __XXXXXX, XXXXXXX_, 
        ________, _______X, XXXXXXXX, _____XXX, XXXXXX__, _____XXX, XXXXXXXX, XX____XX, XXXXX___, ________, _XXXXXXX, _____XXX, XXXXX___, XXXXXXXX, XXXXX___, _____XXX, XXXXXX__, _XXXXXXX, XXXXXXXX, X_______, XXXXXXXX, X__XXXXX, XX____XX, XXXXXXXX, 
        XXX____X, XXXXXX__, _XXXXXXX, ________,
  XXXXXXXX, ________, XXXXXXX_, _XXXXXXX, ___XXXXX, XX______, _XXXXXXX, _XXXXXX_, ______XX, XXXXXXX_, ________, __XXXXXX, XXX_____, ______XX, XXXXXXX_, _XXXXXXX, ___XXXXX, XX______, XXXXXXXX, X_______, ___XXXXX, XXXX___X, XXXXX___, ____XXXX, XXXXX___, 
        ________, _______X, XXXXXXXX, _____XXX, XXXXXX__, _______X, XXXXXXXX, ______XX, XXXXX___, ________, _XXXXXXX, ______XX, XXXXX___, __XXXXXX, XXX_____, ______XX, XXXXXX__, ___XXXXX, XX_XXXXX, X_______, _XXXXXXX, X__XXXXX, XX______, XXXXXXXX, 
        X______X, XXXXXX__, _XXXXXXX, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmx191y249 = {
  420, /* XSize */
  34, /* YSize */
  53, /* BytesPerLine */
  1, /* BitsPerPixel */
  acx191y249,  /* Pointer to picture data (indices) */
  &Palx191y249  /* Pointer to palette */
};

/* *** End of file *** */
