/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: x219y170
* Dimensions:  326 * 34
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsx219y170[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palx219y170 = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsx219y170[0]
};

static GUI_CONST_STORAGE unsigned char acx219y170[] = {
  ________, ____XXXX, XXXXXX__, ________, ________, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXXXX__, ________, ________, ________, ________, ________, ________, XXXXXXX_, ________, ________, ________, ____XXXX, 
        XXXXXXX_, ______XX, XXXXXXXX, ________, ________, ________, ________, ________, XXXXXXX_, ________, ____XXXX, XXX_____, ________, ________, ________, ________,
  ________, ____XXXX, XXXXXX__, ________, ________, ________, ________, ________, ________, ________, ________, _XXXXXXX, ______XX, XXXXXX__, ________, ________, ________, ________, ________, ________, XXXXXXX_, ________, ________, ________, ____XXXX, 
        XXXXXXX_, _____XXX, XXXXXXXX, ________, ________, ________, ________, ________, XXXXXXX_, ________, ____XXXX, XXX_____, ________, ________, ________, ________,
  ________, ___XXXXX, XXXXXX__, ________, ________, ________, ________, ________, ________, ________, ________, _XXXXXXX, ______XX, XXXXX___, ________, ________, ________, ________, ________, _______X, XXXXXX__, ________, ________, ________, ____XXXX, 
        XXXXXXX_, _____XXX, XXXXXXXX, ________, ________, ________, ________, ________, XXXXXXX_, ________, ___XXXXX, XX______, ________, ________, ________, ________,
  ________, ___XXXXX, XXXXXX__, ________, ________, ________, ________, ________, ________, ________, ________, _XXXXXXX, ______XX, XXXXX___, ________, ________, ________, ________, ________, _______X, XXXXXX__, ________, ________, ________, ____XXXX, 
        XXXXXXX_, _____XXX, XXXXXXXX, ________, ________, ________, ________, ________, XXXXXXX_, ________, ___XXXXX, XX______, ________, ________, ________, ________,
  ________, ___XXXXX, XXXXXX__, ________, ________, ________, ________, ________, ________, ________, ________, _XXXXXXX, ______XX, XXXXX___, ________, ________, ________, ________, ________, _______X, XXXXXX__, ________, ________, ________, ____XXXX, 
        XXXXXXX_, ____XXXX, XXXXXXXX, ________, ________, ________, ________, ________, XXXXXXX_, ________, ___XXXXX, XX______, ________, ________, ________, ________,
  ________, __XXXXXX, XXXXXX__, ________, ________, ________, ________, ________, ________, ________, ________, _XXXXXX_, ______XX, XXXXX___, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ____XXXX, 
        XXXXXXX_, ____XXXX, XXXXXXXX, ________, ________, ________, ________, ________, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________,
  ________, __XXXXXX, XXXXXX__, ________, ________, ________, ________, ________, ________, ________, ________, XXXXXXX_, _____XXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, 
        XXXXXXX_, ___XXXXX, XXXXXXX_, ________, ________, ________, ________, _______X, XXXXXX__, ________, ________, ________, ________, ________, ________, ________,
  ________, __XXXXXX, XXXXXX__, _____XXX, XXXX_XXX, XXX_____, ____XXXX, XXXXX___, _______X, XXXXXXXX, _____XXX, XXXXXXXX, XXX__XXX, XXXX_XXX, XXXX____, ____XXXX, XXXXX___, _______X, XXXXXXXX, ______XX, XXXXX___, ___XXXXX, XXXX____, ________, ___XXXXX, 
        XXXXXXX_, ___XXXXX, XXXXXXX_, _____XXX, XXXXXX__, ________, XXXXXXXX, X______X, XXXXXX_X, XXXXXX__, __XXXXXX, X__XXXXX, XX_XXXXX, X_______, __XXXXXX, XXX_____,
  ________, _XXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XXXX____, __XXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XXXXX___, __XXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, XX____XX, XXXXX___, _XXXXXXX, XXXXXX__, ________, ___XXXXX, 
        XXXXXXX_, ___XXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, ______XX, XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXX_, __XXXXXX, X__XXXXX, XXXXXXXX, XX______, XXXXXXXX, XXXXX___,
  ________, _XXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, ____XXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, ____XXXX, XXXXXXXX, XXX___XX, XXXXX___, XXXXXXXX, XXXXXXX_, ________, ___XXXXX, 
        XXXXXXX_, __XXXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX, X____XXX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXXX, __XXXXXX, X__XXXXX, XXXXXXXX, XXX____X, XXXXXXXX, XXXXXX__,
  ________, XXXXXXX_, XXXXXX__, _____XXX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, XXX___XX, XXXXX__X, XXXXXXXX, XXXXXXX_, ________, ___XXXXX, 
        XXXXXXX_, __XXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXXX, __XXXXXX, X__XXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXX__,
  ________, XXXXXXX_, XXXXXX__, ____XXXX, XXXX__XX, XXXXX___, XXXXXXX_, _XXXXXXX, __XXXXXX, XX__XXXX, XXX____X, XXXXXX__, ____XXXX, XXXX__XX, XXXXX__X, XXXXXXX_, _XXXXXXX, __XXXXXX, XX__XXXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXXX_, ________, __XXXXXX, 
        XXXXXXX_, _XXXXXXX, XXXXXX__, XXXXXXXX, __XXXXXX, X__XXXXX, XXX__XXX, XXXX__XX, XXXXXX__, XXXXXXXX, _XXXXXXX, __XXXXXX, XX__XXXX, XXX__XXX, XXXXX__X, XXXXXX__,
  ________, XXXXXXX_, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX__XX, XXXXX___, XXXXXXX_, ________, __XXXXXX, 
        XXXXXXX_, _XXXXXXX, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__,
  _______X, XXXXXX__, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX__XX, XXXXX___, XXXXXXX_, ________, __XXXXXX, 
        XXXXXXX_, _XXXXXXX, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__,
  _______X, XXXXXX__, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, _XXXXXXX, X___XXXX, XXX__XXX, XXXX__XX, XXXXX___, XXXXXXX_, ________, __XXXXXX, 
        XXXXXXX_, XXXXXXXX, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__,
  _______X, XXXXXX__, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX____X, XXXXXX__, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, _XXXXXXX, X__XXXXX, XXX__XXX, XXXX__XX, XXXX____, XXXXXXX_, ________, __XXXXXX, 
        _XXXXXX_, XXXXXX_X, XXXXXX__, XXXXXX__, __XXXXXX, X__XXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__,
  ______XX, XXXXXX__, XXXXXX__, ___XXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, _XXXXXXX, X___XXXX, XX____XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, _XXXXXXX, X__XXXXX, XX__XXXX, XXX___XX, XXXX___X, XXXXXX__, ________, _XXXXXX_, 
        _XXXXXX_, XXXXXX_X, XXXXX___, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX___,
  ______XX, XXXXX___, XXXXXX__, ___XXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, _XXXXXXX, XX______, ______XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, _XXXXXXX, XX______, ____XXXX, XXX_____, ______XX, XXXXXX__, ________, _XXXXXX_, 
        _XXXXXXX, XXXXXX_X, XXXXX___, ________, XXXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX___,
  ______XX, XXXXX___, XXXXXX__, ___XXXXX, XX___XXX, XXXX__XX, XXXXXXXX, XXXXXXX_, __XXXXXX, XXXX____, ______XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXXXXX, XXXXXXX_, __XXXXXX, XXXX____, ____XXXX, XXX_____, ____XXXX, XXXXXX__, ________, _XXXXXX_, 
        _XXXXXXX, XXXXX__X, XXXXX___, ______XX, XXXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXXXXXXX, XXXXX___,
  _____XXX, XXXXX___, XXXXXX__, ___XXXXX, XX___XXX, XXXX__XX, XXXXXXXX, XXXXXXX_, __XXXXXX, XXXXXX__, ______XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXXXXX, XXXXXXX_, __XXXXXX, XXXXXX__, ____XXXX, XXX_____, __XXXXXX, XXXXXX__, ________, _XXXXXX_, 
        _XXXXXXX, XXXXX__X, XXXXX___, ____XXXX, XXXXXXXX, __XXXXXX, X_______, _____XXX, XXXX___X, XXXXXX__, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXXXXXXX, XXXXX___,
  _____XXX, XXXXXXXX, XXXXXX__, ___XXXXX, XX___XXX, XXXX__XX, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, ______XX, XXXXX___, ___XXXXX, XX___XXX, XXXX__XX, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, ____XXXX, XXX_____, XXXXXXXX, XXXXXX__, ________, _XXXXXX_, 
        _XXXXXXX, XXXX__XX, XXXXX___, __XXXXXX, XXXXXXXX, __XXXXXX, X_______, _____XXX, XXXX___X, XXXXXX__, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXXXXXXX, XXXXX___,
  _____XXX, XXXXXXXX, XXXXXX__, __XXXXXX, X___XXXX, XXX__XXX, XXXXXXXX, XXXXXX__, ______XX, XXXXXXXX, _____XXX, XXXX____, __XXXXXX, X___XXXX, XXX__XXX, XXXXXXXX, XXXXXX__, ______XX, XXXXXXXX, ___XXXXX, XX____XX, XXXXXXXX, XXXXX___, ________, XXXXXX__, 
        _XXXXXXX, XXXX__XX, XXXX____, XXXXXXXX, XXXXXXX_, _XXXXXXX, ________, ____XXXX, XXX___XX, XXXXX__X, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XXXXXXXX, XXXX____,
  ____XXXX, XXXXXXXX, XXXXXX__, __XXXXXX, X___XXXX, XXX__XXX, XXXX____, ________, _______X, XXXXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX__XXX, XXXX____, ________, _______X, XXXXXXXX, X__XXXXX, XX___XXX, XXXXX_XX, XXXXX___, ________, XXXXXX__, 
        _XXXXXXX, XXXX__XX, XXXX___X, XXXXXXX_, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX__X, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX______, ________,
  ____XXXX, XXXXXXXX, XXXXXX__, __XXXXXX, X___XXXX, XXX__XXX, XXXX____, ________, ________, _XXXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX__XXX, XXXX____, ________, ________, _XXXXXXX, X__XXXXX, XX__XXXX, XXX___XX, XXXXX___, ________, XXXXXX__, 
        _XXXXXXX, XXX___XX, XXXX__XX, XXXXX___, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX__X, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX______, ________,
  ___XXXXX, XXX____X, XXXXXX__, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXX__, _XXXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXXX_, _XXXXXXX, X__XXXXX, XX__XXXX, XXX___XX, XXXXX___, ________, XXXXXX__, 
        _XXXXXXX, XXX___XX, XXXX__XX, XXXXX___, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX__X, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX____,
  ___XXXXX, XXX____X, XXXXXX__, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXX__, _XXXXXXX, X____XXX, XXXX____, __XXXXXX, X___XXXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXXX_, _XXXXXXX, X__XXXXX, XX__XXXX, XXX___XX, XXXXX___, ________, XXXXXX__, 
        _XXXXXXX, XX___XXX, XXXX__XX, XXXXX___, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX__X, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX____,
  ___XXXXX, XXX____X, XXXXXX__, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X__XXXXX, XX____XX, XXXX____, _______X, XXXXX___, 
        _XXXXXXX, XX___XXX, XXX__XXX, XXXX____, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX__XX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX_____,
  __XXXXXX, XX_____X, XXXXXX__, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, ____XXXX, XXX_____, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X__XXXXX, XX___XXX, XXXX____, _______X, XXXXX___, 
        _XXXXXXX, X____XXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX__XX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX_____,
  __XXXXXX, XX_____X, XXXXXX__, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, ____XXXX, XXXX____, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X__XXXXX, XX___XXX, XXXX____, _______X, XXXXX___, 
        _XXXXXXX, X____XXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX__XX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX_____,
  __XXXXXX, XX_____X, XXXXXX__, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX__X, XXXXXX__, XXXXXXXX, ____XXXX, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXX___XX, XXXXX__X, XXXXXX__, XXXXXXXX, __XXXXXX, X__XXXXX, XX___XXX, XXXX____, _______X, XXXXX___, 
        _XXXXXXX, X____XXX, XXX__XXX, XXXX___X, XXXXXX__, XXXXXXX_, __XXXXXX, X__XXXXX, XX___XXX, XXXX__XX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, X___XXXX, XXX_____,
  _XXXXXXX, X______X, XXXXXX__, _XXXXXXX, ___XXXXX, XX__XXXX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXX_, _XXXXXXX, ___XXXXX, XX__XXXX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXX_, __XXXXXX, X__XXXXX, XXXXXXXX, XXXX____, _______X, XXXXX___, 
        _XXXXXXX, ____XXXX, XXX__XXX, XXXXXXXX, XXXXXX__, XXXXXXXX, XXXXXXXX, ___XXXXX, XX___XXX, XXXX__XX, XXXXX__X, XXXXXX__, _XXXXXXX, __XXXXXX, XXXXXXXX, XX______,
  _XXXXXXX, X______X, XXXXXX__, XXXXXXX_, __XXXXXX, X___XXXX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXX__, XXXXXXX_, __XXXXXX, X___XXXX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXX_, _XXXXXXX, ___XXXXX, XXXXXXXX, XXX_____, ______XX, XXXX____, 
        _XXXXXXX, ____XXXX, XX___XXX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, __XXXXXX, X___XXXX, XXX__XXX, XXXX__XX, XXXXX___, XXXXXXX_, __XXXXXX, XXXXXXXX, XX______,
  _XXXXXXX, X______X, XXXXXX__, XXXXXXX_, __XXXXXX, X____XXX, XXXXXXXX, XX______, XXXXXXXX, XXXXX___, ____XXXX, XXXXXX__, XXXXXXX_, __XXXXXX, X____XXX, XXXXXXXX, XX______, XXXXXXXX, XXXXX___, _XXXXXXX, ___XXXXX, XXXXXXXX, XXX_____, ______XX, XXXX____, 
        _XXXXXX_, ____XXXX, XX___XXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXX__, __XXXXXX, X___XXXX, XXX__XXX, XXXX__XX, XXXXX___, XXXXXXX_, ___XXXXX, XXXXXXXX, ________,
  XXXXXXXX, _______X, XXXXXX__, XXXXXXX_, __XXXXXX, X______X, XXXXXXXX, ________, __XXXXXX, XXX_____, _____XXX, XXXXXX__, XXXXXXX_, __XXXXXX, X______X, XXXXXXXX, ________, __XXXXXX, XXX_____, _XXXXXXX, _____XXX, XXXX_XXX, XXX_____, ______XX, XXXX____, 
        _XXXXXX_, ____XXXX, XX_____X, XXXXXX_X, XXXXX___, ___XXXXX, XXXX____, __XXXXXX, X___XXXX, XXX__XXX, XXXX__XX, XXXXX___, XXXXXXX_, _____XXX, XXXXXX__, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmx219y170 = {
  326, /* XSize */
  34, /* YSize */
  41, /* BytesPerLine */
  1, /* BitsPerPixel */
  acx219y170,  /* Pointer to picture data (indices) */
  &Palx219y170  /* Pointer to palette */
};

/* *** End of file *** */
