/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: 1111
* Dimensions:  11 * 11
* NumColors:   4
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colors1111[] = {
     0xCEAD94,0x00FF00,0xCEAD94,0xCEAD94
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Pal1111 = {
  4,	/* number of entries */
  0, 	/* No transparency */
  &Colors1111[0]
};

static GUI_CONST_STORAGE unsigned char ac1111[] = {
  0xAA, 0x56, 0xA8,
  0xA5, 0x55, 0x68,
  0x95, 0x55, 0x58,
  0x95, 0x55, 0x58,
  0x55, 0x55, 0x54,
  0x55, 0x55, 0x54,
  0x55, 0x55, 0x54,
  0x95, 0x55, 0x58,
  0x95, 0x55, 0x58,
  0xA5, 0x55, 0x68,
  0xAA, 0x56, 0xA8
};

GUI_CONST_STORAGE GUI_BITMAP bmOptionFlag = {
  11, /* XSize */
  11, /* YSize */
  3, /* BytesPerLine */
  2, /* BitsPerPixel */
  ac1111,  /* Pointer to picture data (indices) */
  &Pal1111  /* Pointer to palette */
};

/* *** End of file *** */
