/***************************************************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: 12
* Dimensions:  46 * 30
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colors12[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Pal12 = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colors12[0]
};

static GUI_CONST_STORAGE unsigned char ac12[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX___X, XXXXXXX_, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXX__, _XXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX__XXX, XXXXX___, __XXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX___XXX, XXXX____, ___XXX__,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX__XXXX, XXX_____, ____XX__,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, X___XXXX, XX______, _____X__,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, X__XXXXX, X_______, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXX__, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXX__X, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXX__, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__
};

GUI_CONST_STORAGE GUI_BITMAP bm12 = {
  46, /* XSize */
  30, /* YSize */
  6, /* BytesPerLine */
  1, /* BitsPerPixel */
  ac12,  /* Pointer to picture data (indices) */
  &Pal12  /* Pointer to palette */
};

/* *** End of file *** */
