/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsalrmlog_bell[] = {
     0xFFFFFF,0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palalrmlog_bell = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsalrmlog_bell[0]
};

static GUI_CONST_STORAGE unsigned char acalrmlog_bell[] = {
  ______XX, ________,
  ______XX, ________,
  ____XXXX, XX______,
  ___XXXXX, XXX_____,
  ___XX___, _XX_____,
  __XX____, __XX____,
  __XX____, __XX____,
  _XX_____, ___XX___,
  _XX_____, ___XX___,
  _XX_____, ___XX___,
  XX______, ____XX__,
  XX______, ____XX__,
  XXXXXXXX, XXXXXX__,
  ________, ________,
  ____XXXX, XX______,
  _____XXX, X_______
};

GUI_CONST_STORAGE GUI_BITMAP bmalrmlog_bell = {
  16, /* XSize */
  16, /* YSize */
  2, /* BytesPerLine */
  1, /* BitsPerPixel */
  acalrmlog_bell,  /* Pointer to picture data (indices) */
  &Palalrmlog_bell  /* Pointer to palette */
};

/* *** End of file *** */
