/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: Anesthesia_System
* Dimensions:  325 * 29
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsAnesthesia_System[] = {
     0x000000,0xCDCECD
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalAnesthesia_System = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsAnesthesia_System[0]
};

static GUI_CONST_STORAGE unsigned char acAnesthesia_System[] = {
  XXXXXXXX, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXX_____, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XX______, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XX______, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XX_____X, XXXXXX__, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXX__, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XX_____X, XXXXXX__, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXX__, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XX_____X, XXXXXX__, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXX__, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XX_____X, XXXXXX__, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XX______, _XXXXXX_, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXX___, __X_____, XXXXXXXX, ________, _______X, XXXX____, ________, ___XXXXX, X_______, _______X, XXX_____, ________, XXX_____, X_______, __XXXXXX, ________, _______X, XXXX____, ________, __XXXXXX, _____XXX, XXX_____, ________, _XXXXXXX, XXXXXXXX, 
        XXX_____, __XXXXXX, XXXXXXX_, _____XXX, XXX_____, _XXX____, ________, __XXXX__, ________, ___XXX__, ________, _____XXX, XX_____X, ________, _XX_____, ____X___,
  XXXXX___, __X_____, XXXXXXXX, ________, ________, XXXX____, ________, ____XXXX, X_______, ________, XXX_____, ________, XXX_____, ________, ___XXXXX, ________, ________, XXXX____, ________, ___XXXXX, _____XXX, XX______, ________, __XXXXXX, XXXXXXXX, 
        XXXXX___, ____XXXX, XXXXXXXX, _____XXX, XXX_____, XXXX____, ________, ___XXX__, ________, ___XXX__, ________, ______XX, XX______, ________, ________, ________,
  XXXX____, _XX_____, XXXXXXXX, ________, ________, XXXX____, ________, ____XXXX, ________, ________, XXX_____, _______X, XXX_____, ________, ___XXXXX, ________, ________, XXX_____, ________, ___XXXXX, _____XXX, XX______, ________, __XXXXXX, XXXXXXXX, 
        XXXXXX__, _____XXX, XXXXXXXX, _____XXX, XX______, XXX_____, ________, ___XXX__, ________, __XXXX__, ________, ______XX, XX______, ________, ________, ________,
  XXXX____, _XXX____, _XXXXXXX, ______XX, XXX_____, XXXX____, _XXXXX__, ____XXXX, ______XX, XXX_____, XXXXXX__, ___XXXXX, XXX_____, __XXXX__, ___XXXXX, _____XXX, XX______, XXX_____, _XXXXX__, ___XXXXX, _____XXX, XX_____X, XXXXX___, __XXXXXX, XXXXXXXX, 
        XXXXXXXX, _______X, XXXXXXXX, ______XX, XX_____X, XXX_____, _XXXXX__, ___XXXXX, X_____XX, XXXXXX__, ___XXXXX, ______XX, XX______, _XXXX___, ____XXX_, ________,
  XXXX____, _XXX____, _XXXXXXX, _____XXX, XXX_____, XXXX____, _XXXXX__, ____XXXX, X______X, XXX_____, XXXXXX__, ___XXXXX, XXX_____, XXXXXX__, ___XXXXX, _____XXX, XX______, XXXX____, __XXXX__, ___XXXXX, _____XXX, XX_____X, XXXXX___, __XXXXXX, XXXXXXXX, 
        XXXXXXXX, X_______, XXXXXXXX, X_____XX, XX_____X, XXXX____, __XXXX__, ___XXXXX, X_____XX, XXXXXX__, ___XXXXX, ______XX, XX_____X, XXXXX___, __XXXXX_, ________,
  XXX_____, XXXX____, _XXXXXXX, _____XXX, XXX_____, XXXX____, ________, ____XXXX, X_______, _XXXXXXX, XXXXXX__, ___XXXXX, XXX_____, XXXXXX__, ___XXXXX, ________, ________, XXXX____, ____XXXX, XXXXXXXX, _____XXX, XXXXXXXX, XXXXX___, __XXXXXX, XXXXXXXX, 
        XXXXXXXX, XXX_____, __XXXXXX, X______X, X______X, XXXX____, ____XXXX, XXXXXXXX, X_____XX, XXXXXX__, ________, ______XX, XX_____X, XXXXX___, __XXXXX_, ________,
  XXX_____, XXXX____, __XXXXXX, _____XXX, XXX_____, XXXX____, ________, ____XXXX, XXX_____, ___XXXXX, XXXXXX__, ___XXXXX, XXX_____, XXXXXX__, ___XXXXX, ________, ________, XXXXXX__, ______XX, XXXXXXXX, _____XXX, XX______, ________, __XXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXX____, ___XXXXX, XX_____X, X_____XX, XXXXXX__, ______XX, XXXXXXXX, X_____XX, XXXXXX__, ________, ______XX, XX_____X, XXXXX___, __XXXXX_, ________,
  XXX_____, XXXXX___, __XXXXXX, _____XXX, XXX_____, XXXX____, ________, ___XXXXX, XXXXX___, _____XXX, XXXXXX__, ___XXXXX, XXX_____, XXXXXX__, ___XXXXX, ________, _______X, XXXXXXXX, ________, XXXXXXXX, _____XXX, X_______, ________, __XXXXXX, XXXXXXXX, 
        XX_____X, XXXXX___, ____XXXX, XX_____X, X_____XX, XXXXXXXX, ________, XXXXXXXX, X_____XX, XXXXXX__, ________, _____XXX, XX_____X, XXXXX___, __XXXXX_, ________,
  XX______, ________, __XXXXXX, _____XXX, XXX_____, XXXX____, _XXXXXXX, XXXXXXXX, XXXXXXX_, _______X, XXXXXX__, ___XXXXX, XXX_____, XXXXXX__, ___XXXXX, _____XXX, XXXXXXXX, XXXXXXXX, XX______, __XXXXXX, _____XXX, X_______, ________, __XXXXXX, XXXXXXXX, 
        XX_____X, XXXXXX__, ____XXXX, XXX_____, _____XXX, XXXXXXXX, XX______, __XXXXXX, X_____XX, XXXXXX__, ___XXXXX, XXXXXXXX, XX_____X, XXXXX___, __XXXXX_, ________,
  XX______, ________, ___XXXXX, _____XXX, XXX_____, XXXX____, _XXXXX__, ____XXXX, ______XX, X_______, XXXXXX__, ___XXXXX, XXX_____, XXXXXX__, ___XXXXX, _____XXX, XX______, XXX_____, _XXX____, ___XXXXX, _____XXX, X______X, XXXXX___, __XXXXXX, XXXXXXXX, 
        XX_____X, XXXXXX__, ____XXXX, XXX_____, _____XXX, XXX_____, _XXX____, ___XXXXX, X_____XX, XXXXXX__, ___XXXXX, ______XX, XX_____X, XXXXX___, __XXXXX_, ________,
  XX______, ________, ___XXXXX, _____XXX, XXX_____, XXXX____, _XXXXX__, ____XXXX, ______XX, XXX_____, XXXXXX__, ___XXXXX, XXX_____, XXXXXX__, ___XXXXX, _____XXX, XX______, XXX_____, _XXXXX__, ___XXXXX, _____XXX, X______X, XXXXX___, __XXXXXX, XXXXXXXX, 
        XX_____X, XXXXXX__, ____XXXX, XXXX____, ____XXXX, XXX_____, _XXXXX__, ___XXXXX, X_____XX, XXXXXX__, ___XXXXX, ______XX, XX_____X, XXXXX___, __XXXXX_, ________,
  X______X, XXXXXX__, ___XXXXX, _____XXX, XXX_____, XXXX____, _XXXXX__, ____XXXX, ______XX, XXX_____, XXXXXX__, ___XXXXX, XXX_____, XXXXXX__, ___XXXXX, _____XXX, XX______, XXX_____, _XXXXX__, ___XXXXX, _____XXX, X______X, ________, __XXXXXX, XXXXXXXX, 
        XX_____X, XXXXXX__, ____XXXX, XXXX____, ____XXXX, XXX_____, _XXXXX__, ___XXXXX, X_____XX, XXXXXX__, ___XXXXX, ______XX, XX_____X, XXXXX___, __XXXXX_, ________,
  X_____XX, XXXXXX__, ____XXXX, _____XXX, XXX_____, XXXX____, ________, ____XXXX, ________, ________, XXXXXX__, ________, XXX_____, XXXXXX__, ___XXXXX, ________, ________, XXX_____, ________, ___XXXXX, _____XXX, X_______, ________, __XXXXXX, XXXXXXXX, 
        XX______, ________, ____XXXX, XXXX____, ____XXXX, XXX_____, ________, ___XXXXX, X_______, ___XXX__, ________, ______XX, XX_____X, XXXXX___, __XXXXX_, ________,
  X_____XX, XXXXXX__, ____XXXX, _____XXX, XXX_____, XXXX____, ________, ___XXXXX, X_______, ________, XXXXXX__, ________, XXX_____, XXXXXX__, ___XXXXX, ________, _______X, XXXX____, ________, ___XXXXX, _____XXX, XX______, ________, __XXXXXX, XXXXXXXX, 
        XX______, ________, ___XXXXX, XXXXX___, ___XXXXX, XXXX____, ________, ___XXXXX, X_______, ___XXX__, ________, _____XXX, XX_____X, XXXXX___, __XXXXX_, ________,
  X____XXX, XXXXXXX_, ____XXXX, _____XXX, XXX_____, XXXXX___, ________, __XXXXXX, XX______, ______XX, XXXXXXXX, _______X, XXX_____, XXXXXX__, ___XXXXX, X_______, ______XX, XXXXX___, ________, _XXXXXXX, _____XXX, XXX_____, __XXX___, _XXXXXXX, XXXXXXXX, 
        XXXX____, ________, __XXXXXX, XXXXX___, ___XXXXX, XXXXX___, ________, _XXXXXXX, XXX_____, __XXXXX_, ________, ____XXXX, XX_____X, XXXXX___, _XXXXXXX, ____X___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___
};

GUI_CONST_STORAGE GUI_BITMAP bmAnesthesia_System = {
  325, /* XSize */
  29, /* YSize */
  41, /* BytesPerLine */
  1, /* BitsPerPixel */
  acAnesthesia_System,  /* Pointer to picture data (indices) */
  &PalAnesthesia_System  /* Pointer to palette */
};

/* *** End of file *** */
