/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: arrows_left
* Dimensions:  6 * 9
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsarrows_left[] = {
     0xFFFFFF,0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palarrows_left = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsarrows_left[0]
};

static GUI_CONST_STORAGE unsigned char acarrows_left[] = {
  ___XXX__,
  __XXX___,
  _XXX____,
  XXXX____,
  XXX_____,
  XXXX____,
  _XXX____,
  __XXX___,
  ___XXX__
};

GUI_CONST_STORAGE GUI_BITMAP bmarrows_left = {
  6, /* XSize */
  9, /* YSize */
  1, /* BytesPerLine */
  1, /* BitsPerPixel */
  acarrows_left,  /* Pointer to picture data (indices) */
  &Palarrows_left  /* Pointer to palette */
};

/* *** End of file *** */
