/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: Battery_WB_Bg
* Dimensions:  28 * 16
* NumColors:   4
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsBattery_WB_Bg[] = {
	0x420000,0x725d50,0xa99487,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalBattery_WB_Bg = {
  4,	/* number of entries */
  0, 	/* No transparency */
  &ColorsBattery_WB_Bg[0]
};

static GUI_CONST_STORAGE unsigned char acBattery_WB_Bg[] = {
  0x15, 0x55, 0x55, 0x55, 0x55, 0x55, 0x40,
  0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x60,
  0x57, 0xFF, 0xFF, 0xFF, 0xFF, 0xFD, 0x60,
  0x5F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x60,
  0x5F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x54,
  0x5F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x6A,
  0x5F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x6A,
  0x5F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x6A,
  0x5F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x6A,
  0x5F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x6A,
  0x5F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x6A,
  0x5F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x54,
  0x5F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x60,
  0x57, 0xFF, 0xFF, 0xFF, 0xFF, 0xFD, 0x60,
  0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x60,
  0x15, 0x55, 0x55, 0x55, 0x55, 0x55, 0x40
};

GUI_CONST_STORAGE GUI_BITMAP bmBattery_WB_Bg = {
  28, /* XSize */
  16, /* YSize */
  7, /* BytesPerLine */
  2, /* BitsPerPixel */
  acBattery_WB_Bg,  /* Pointer to picture data (indices) */
  &PalBattery_WB_Bg  /* Pointer to palette */
};

/* *** End of file *** */
