/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: BEKLEMEYi_big
* Dimensions:  259 * 35
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsBEKLEMEYi_big[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalBEKLEMEYi_big = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsBEKLEMEYi_big[0]
};

static GUI_CONST_STORAGE unsigned char acBEKLEMEYi_big[] = {
  XXXXXXXX, XXXXXXXX, XXXXX___, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XX____XX, XXXXX___, ________, __XXXXXX, XXX____X, XXXXXX__, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXX_____, ________, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, XXXXX___, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XX____XX, XXXXX___, ________, _XXXXXXX, XX_____X, XXXXXX__, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXX_____, ________, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, XXXXX___, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, _XXXXXXX, XXXXXXXX, XXXXXXXX, XX____XX, XXXXX___, ________, XXXXXXXX, X______X, XXXXXX__, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXX____, _______X, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXX__, ________, ___XXXXX, XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, _XXXXXXX, XXXXXXXX, XXXXXXXX, XX____XX, XXXXX___, _______X, XXXXXXXX, _______X, XXXXXX__, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXX____, _______X, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXX___X, XXXXXXX_, ________, __XXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XX____XX, XXXXX___, ______XX, XXXXXXX_, _______X, XXXXXX__, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXX____, _______X, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXX___X, XXXXXXX_, ________, __XXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XX____XX, XXXXX___, _____XXX, XXXXXX__, _______X, XXXXXX__, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXX____, _______X, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, ________, _XXXXXXX, X___XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXX_, ________, ___XXXXX, XXXX____, _XXXXXXX, ________, ________, ______XX, XXXXX___, ____XXXX, XXXXXX__, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXXX, XXXXX___, ______XX, XXXXXXXX, XX______, ___XXXXX, XX______, ________, ________, _XXXXXXX, ________, _XXXXXXX, X___XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, ____XXXX, XXXX____, _XXXXXXX, ________, ________, ______XX, XXXXX___, ___XXXXX, XXXXX___, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, XXXXX___, ______XX, XXX_XXXX, XX______, ___XXXXX, XX______, ________, ________, _XXXXXXX, X_______, XXXXXXXX, ____XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, _____XXX, XXXX____, _XXXXXXX, ________, ________, ______XX, XXXXX___, __XXXXXX, XXXX____, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, XXXXX___, ______XX, XXX_XXXX, XX______, ___XXXXX, XX______, ________, ________, __XXXXXX, X_______, XXXXXXX_, ____XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, _____XXX, XXXX____, _XXXXXXX, ________, ________, ______XX, XXXXX___, __XXXXXX, XXX_____, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, XXXXX___, ______XX, XXX_XXXX, XX______, ___XXXXX, XX______, ________, ________, __XXXXXX, XX_____X, XXXXXXX_, ____XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, _____XXX, XXXX____, _XXXXXXX, ________, ________, ______XX, XXXXX___, _XXXXXXX, XX______, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, XXXXXX__, _____XXX, XXX_XXXX, XX______, ___XXXXX, XX______, ________, ________, ___XXXXX, XX_____X, XXXXXX__, ____XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, _____XXX, XXXX____, _XXXXXXX, ________, ________, ______XX, XXXXX___, XXXXXXXX, X_______, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, _XXXXX__, _____XXX, XX__XXXX, XX______, ___XXXXX, XX______, ________, ________, ____XXXX, XXX___XX, XXXXX___, ____XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, ____XXXX, XXX_____, _XXXXXXX, ________, ________, ______XX, XXXXX__X, XXXXXXXX, ________, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, _XXXXX__, _____XXX, XX__XXXX, XX______, ___XXXXX, XX______, ________, ________, ____XXXX, XXXX_XXX, XXXXX___, ____XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, ___XXXXX, XXX_____, _XXXXXXX, ________, ________, ______XX, XXXXX_XX, XXXXXXX_, ________, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, _XXXXX__, _____XXX, XX__XXXX, XX______, ___XXXXX, XX______, ________, ________, _____XXX, XXXX_XXX, XXXX____, ____XXXX, XXXX____, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, _XXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, ________, _______X, XXXXXX__, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, _XXXXXX_, _XXXXXX_, ____XXXX, XX__XXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXX____, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, _XXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, ________, _______X, XXXXXX__, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, _XXXXXX_, __XXXXX_, ____XXXX, X___XXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ______XX, XXXXXXXX, XXX_____, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, X_______, _______X, XXXXXX__, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, _XXXXXX_, __XXXXX_, ____XXXX, X___XXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, _______X, XXXXXXXX, XX______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, _XXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, X_______, _______X, XXXXXX__, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, _XXXXXX_, __XXXXX_, ____XXXX, X___XXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, _______X, XXXXXXXX, XX______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, _XXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XX______, _______X, XXXXXX__, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, _XXXXXX_, __XXXXXX, ___XXXXX, X___XXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, XXXXXXXX, X_______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XX_XXXXX, XXX_____, _______X, XXXXXX__, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, _XXXXXX_, __XXXXXX, ___XXXXX, X___XXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, _XXXXXXX, X_______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXX_, ________, ___XXXXX, XXXX____, _XXXXXXX, ________, ________, ______XX, XXXXXXXX, X__XXXXX, XXX_____, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, ___XXXXX, ___XXXXX, ____XXXX, XX______, ___XXXXX, XX______, ________, ________, ________, _XXXXXXX, ________, ____XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, _____XXX, XXXX____, _XXXXXXX, ________, ________, ______XX, XXXXXXXX, ____XXXX, XXXX____, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, ___XXXXX, ___XXXXX, ____XXXX, XX______, ___XXXXX, XX______, ________, ________, ________, _XXXXXXX, ________, ____XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, ______XX, XXXXX___, _XXXXXXX, ________, ________, ______XX, XXXXXXX_, _____XXX, XXXXX___, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, ___XXXXX, X_XXXXXX, ____XXXX, XX______, ___XXXXX, XX______, ________, ________, ________, _XXXXXXX, ________, ____XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, ______XX, XXXXX___, _XXXXXXX, ________, ________, ______XX, XXXXXX__, _____XXX, XXXXX___, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, ___XXXXX, X_XXXXXX, ____XXXX, XX______, ___XXXXX, XX______, ________, ________, ________, _XXXXXXX, ________, ____XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, ______XX, XXXXX___, _XXXXXXX, ________, ________, ______XX, XXXXX___, ______XX, XXXXXX__, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, ____XXXX, X_XXXXX_, ____XXXX, XX______, ___XXXXX, XX______, ________, ________, ________, _XXXXXXX, ________, ____XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, ______XX, XXXXX___, _XXXXXXX, ________, ________, ______XX, XXXXX___, ______XX, XXXXXXX_, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, ____XXXX, X_XXXXX_, ____XXXX, XX______, ___XXXXX, XX______, ________, ________, ________, _XXXXXXX, ________, ____XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, ______XX, XXXXX___, _XXXXXXX, ________, ________, ______XX, XXXXX___, _______X, XXXXXXX_, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, ____XXXX, XXXXXXX_, ____XXXX, XX______, ___XXXXX, XX______, ________, ________, ________, _XXXXXXX, ________, ____XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, _____XXX, XXXXX___, _XXXXXXX, ________, ________, ______XX, XXXXX___, ________, XXXXXXXX, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, ____XXXX, XXXXXXX_, ____XXXX, XX______, ___XXXXX, XX______, ________, ________, ________, _XXXXXXX, ________, ____XXXX, XXXX____, ________, ________,
  XXXXXXX_, ________, ___XXXXX, XXXX____, _XXXXXXX, ________, ________, ______XX, XXXXX___, ________, XXXXXXXX, _______X, XXXXXX__, ________, ________, ____XXXX, XXX_____, ________, ________, _XXXXXX_, _____XXX, XXXXXX__, ____XXXX, XX______, ___XXXXX, XX______, ________, ________, ________, _XXXXXXX, ________, ____XXXX, XXXX____, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXX___, ________, _XXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _XXXXXX_, _____XXX, XXXXXX__, ____XXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, _XXXXXXX, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXX___, ________, __XXXXXX, XX_____X, XXXXXXXX, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _XXXXXX_, _____XXX, XXXXXX__, ____XXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, _XXXXXXX, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXX___, ________, __XXXXXX, XX_____X, XXXXXXXX, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _XXXXXX_, _____XXX, XXXXXX__, ____XXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, _XXXXXXX, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXX___, ________, ___XXXXX, XXX____X, XXXXXXXX, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _XXXXXX_, ______XX, XXXXX___, ____XXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, _XXXXXXX, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXX___, ________, ___XXXXX, XXXX___X, XXXXXXXX, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _XXXXXX_, ______XX, XXXXX___, ____XXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, _XXXXXXX, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXX__, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXX___, ________, ____XXXX, XXXX___X, XXXXXXXX, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _XXXXXX_, ______XX, XXXXX___, ____XXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, _XXXXXXX, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
};

GUI_CONST_STORAGE GUI_BITMAP bmStandby_Icon_Turkish = {
  280, /* XSize */
  35, /* YSize */
  35, /* BytesPerLine */
  1, /* BitsPerPixel */
  acBEKLEMEYi_big,  /* Pointer to picture data (indices) */
  &PalBEKLEMEYi_big  /* Pointer to palette */
};

/* *** End of file *** */
