/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: BEKLEMEYi_small
* Dimensions:  148 * 20
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsBEKLEMEYi_small[] = {
     0xFFFFFF,0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalBEKLEMEYi_small = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &ColorsBEKLEMEYi_small[0]
};

static GUI_CONST_STORAGE unsigned char acBEKLEMEYi_small[] = {
  XXXXXXXX, XXXXX___, ___XXXXX, XXXXXXXX, XX_XXXX_, _______X, XXXX__XX, XX______, _______X, XXXXXXXX, XXXXXX_X, XXXXX___, ____XXXX, XX_____X, XXXXXXXX, XXXXXXXX, XX______, ____XXXX, XXXXXXXX,XXXXXXXX,
  XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, XX_XXXX_, ______XX, XXX___XX, XX______, _______X, XXXXXXXX, XXXXXX_X, XXXXXX__, ___XXXXX, XX_____X, XXXXXXXX, XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX,XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, XX_XXXX_, _____XXX, XX____XX, XX______, _______X, XXXXXXXX, XXXXXX_X, XXXXXX__, ___XXXXX, XX_____X, XXXXXXXX, XXXXXX_X, XXXX____, __XXXXX_, XXXXXXXX,XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, XX_XXXX_, ____XXXX, X_____XX, XX______, _______X, XXXXXXXX, XXXXXX_X, XXXXXX__, ___XXXXX, XX_____X, XXXXXXXX, XXXXXX__, XXXX____, __XXXX__, XXXXXXXX,XXXXXXXX,
  XXXX____, ___XXXXX, ___XXXX_, ________, ___XXXX_, ___XXXXX, ______XX, XX______, _______X, XXX_____, _______X, XXX_XX__, ___XX_XX, XX_____X, XXX_____, ________, XXXXX___, _XXXXX__, XXXX____,________,
  XXXX____, ____XXXX, ___XXXX_, ________, ___XXXX_, __XXXXX_, ______XX, XX______, _______X, XXX_____, _______X, XXX_XXX_, __XXX_XX, XX_____X, XXX_____, ________, _XXXX___, _XXXX___, XXXX____,________,
  XXXX____, ____XXXX, ___XXXX_, ________, ___XXXX_, _XXXXX__, ______XX, XX______, _______X, XXX_____, _______X, XXX_XXX_, __XXX_XX, XX_____X, XXX_____, ________, __XXXX__, XXXX____, XXXX____,________,
  XXXX____, ___XXXX_, ___XXXX_, ________, ___XXXX_, XXXXX___, ______XX, XX______, _______X, XXX_____, _______X, XXX_XXX_, __XXX_XX, XX_____X, XXX_____, ________, __XXXXXX, XXXX____, XXXX____,________,
  XXXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, X__XXXXX, XXXXX___, ______XX, XX______, _______X, XXXXXXXX, XXXXX__X, XXX_XXX_, __XXX_XX, XX_____X, XXXXXXXX, XXXXX___, ___XXXXX, XXX_____, XXXXXXXX,XXXXXX__,
  XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, X__XXXXX, XXXXXX__, ______XX, XX______, _______X, XXXXXXXX, XXXXX__X, XXX__XXX, _XXX__XX, XX_____X, XXXXXXXX, XXXXX___, ____XXXX, XX______, XXXXXXXX,XXXXXX__,
  XXXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, X__XXXXX, XXXXXXX_, ______XX, XX______, _______X, XXXXXXXX, XXXXX__X, XXX__XXX, _XXX__XX, XX_____X, XXXXXXXX, XXXXX___, ____XXXX, XX______, XXXXXXXX,XXXXXX__,
  XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, X__XXXXX, X__XXXX_, ______XX, XX______, _______X, XXXXXXXX, XXXXX__X, XXX__XXX, _XXX__XX, XX_____X, XXXXXXXX, XXXXX___, _____XXX, X_______, XXXXXXXX,XXXXXX__,
  XXXX____, ____XXXX, X__XXXX_, ________, ___XXXXX, ___XXXXX, ______XX, XX______, _______X, XXX_____, _______X, XXX__XXX, _XXX__XX, XX_____X, XXX_____, ________, _____XXX, X_______, XXXX____,________,
  XXXX____, _____XXX, X__XXXX_, ________, ___XXXX_, ____XXXX, ______XX, XX______, _______X, XXX_____, _______X, XXX___XX, _XX___XX, XX_____X, XXX_____, ________, _____XXX, X_______, XXXX____,________,
  XXXX____, _____XXX, X__XXXX_, ________, ___XXXX_, _____XXX, X_____XX, XX______, _______X, XXX_____, _______X, XXX___XX, XXX___XX, XX_____X, XXX_____, ________, _____XXX, X_______, XXXX____,________,
  XXXX____, ____XXXX, X__XXXX_, ________, ___XXXX_, _____XXX, XX____XX, XX______, _______X, XXX_____, _______X, XXX___XX, XXX___XX, XX_____X, XXX_____, ________, _____XXX, X_______, XXXX____,________,
  XXXXXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX, XX_XXXX_, ______XX, XX____XX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXX_X, XXX___XX, XXX___XX, XX_____X, XXXXXXXX, XXXXXX__, _____XXX, X_______, XXXXXXXX,XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, XX_XXXX_, ______XX, XXX___XX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXX_X, XXX___XX, XXX___XX, XX_____X, XXXXXXXX, XXXXXX__, _____XXX, X_______, XXXXXXXX,XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, XX_XXXX_, _______X, XXXX__XX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXX_X, XXX____X, XX____XX, XX_____X, XXXXXXXX, XXXXXX__, _____XXX, X_______, XXXXXXXX,XXXXXXXX,
  XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, XX_XXXX_, ________, XXXX__XX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXX_X, XXX____X, XX____XX, XX_____X, XXXXXXXX, XXXXXX__, _____XXX, X_______, XXXXXXXX,XXXXXXXX,
};

GUI_CONST_STORAGE GUI_BITMAP bmlittle_standby_Turkish = {
  156, /* XSize */
  20, /* YSize */
  20, /* BytesPerLine */
  1, /* BitsPerPixel */
  acBEKLEMEYi_small,  /* Pointer to picture data (indices) */
  &PalBEKLEMEYi_small  /* Pointer to palette */
};

/* *** End of file *** */
