/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert-Demo V5.26.                            *
*        Compiled Aug  8 2014, 14:40:24                              *
*                                                                    *
*        (c) 2002-2014  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2014  Segger Microcontroller GmbH & Co. KG         *
*        www.segger.com                                              *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: electric_quantity                                     *
* Dimensions:  6 * 10                                                *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmelectric_quantity;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorselectric_quantity[] = {
  //0x000000, 0xFFFFFF
	0x00c900, 0x00ff00
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palelectric_quantity = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorselectric_quantity[0]
};

static GUI_CONST_STORAGE unsigned char _acelectric_quantity[] = {
  X____X__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X____X__
};

GUI_CONST_STORAGE GUI_BITMAP bmelectric_quantity = {
  6, // xSize
  10, // ySize
  1, // BytesPerLine
  1, // BitsPerPixel
  _acelectric_quantity,  // Pointer to picture data (indices)
  &_Palelectric_quantity   // Pointer to palette
};

/*************************** End of file ****************************/
