/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: hsp2
* Dimensions:  341 * 39
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorshsp2[] = {
     0x0800C5,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palhsp2 = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorshsp2[0]
};

static GUI_CONST_STORAGE unsigned char achsp2[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XX______, ________, ______XX, XXXXXXXX, XXXXXXXX, X_______, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, _____XXX, XXX__XXX, XXX_____, ________, ________, ______XX, XXXXXXXX, X_______, ________, ______XX, XX______, ________, ________, ________, 
        ______XX, XX______, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, _______X, XXXXXXXX, __XXXXXX, ________, ________, ____XXXX, ________, ________, ____X___,
  XXXXXX__, ________, ___XXXXX, XXXXXXXX, XXXXXX__, _____XXX, XX______, _XXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXX_____, _X___XXX, XXXXXX__, ________, ___XXXX_, ________, _XXXXXXX, XXXXX___, ________, __XXXXXX, XX______, ___XXXX_, ________, _XXXX___, 
        ______XX, XXXXX___, ________, __XXXXXX, XX______, ____XXXX, XXXXXXXX, XXXXXXXX, ________, XXXXX___, ___XXXXX, __XXXXXX, XXX_____, ________, XXXXXXXX, XXX_____, ________, XXXXX___,
  XXXXXXX_, ________, __XXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXX___, ___XXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXX___, _____XXX, XXXXXXX_, ________, __XXXXXX, X_______, ___XXXXX, XXXXXX__, ________, _XXXXXXX, XX______, XXXXXXX_, ________, _XXXXXXX, 
        ______XX, XXXXXXX_, ________, _XXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, ________, __XXXXXX, XXXX____, _______X, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXX_, ________, _XXXXXXX, XXXXXXXX, XX______, _XXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XXXXX___, __XXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, ________, __XXXXXX, XXX_____, ____XXXX, XXXXXX__, ________, XXXXXXXX, XX_____X, XXXXXXX_, ________, _XXXXXXX, 
        X_____XX, XXXXXXX_, ________, _XXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXXXXX, X_______, __XXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXXXXXX, X_______, _XXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, ________, __XXXXXX, XXX_____, _____XXX, XXXXXXX_, ________, XXXXXXXX, XX____XX, XXXXXXX_, ________, _XXXXXXX, 
        XX____XX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX, XXX_____, __XXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXXXXXX, ________, XXXXXXXX, XXXXXXXX, ________, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX, ________, __XXXXXX, XXXX____, _____XXX, XXXXXXX_, ________, XXXXXXXX, XX___XXX, XXXXXXX_, ________, _XXXXXXX, 
        XXX___XX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XX______, __XXXXXX, XXXXXXXX, XXXX____, __XXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXXXXX_, _______X, XXXXXXXX, XXXXXXXX, ________, _XXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX, ________, __XXXXXX, XXXX____, ______XX, XXXXXXX_, ________, XXXXXXXX, XX__XXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXX___XX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX, X_______, _XXXXXXX, XXXXXXXX, XXXXX___, __XXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXXXX__, _______X, XXXXXXXX, XXXXXXXX, X_______, _XXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XX___XXX, XXXXXXXX, ________, __XXXXXX, XXXX____, ______XX, XXXXXXX_, ________, XXXXXXXX, XX__XXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXX__XX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX, ________, _XXXXXXX, XXXXXXXX, XXXXXX__, __XXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXXXXX, X_______, __XXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, ________, __XXXXXX, XXXX____, ______XX, XXXXXXX_, ________, XXXXXXXX, XX__XXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXX__XX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX, ________, _XXXXXXX, XXXXXXXX, XXXXXXX_, __XXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXXXXX, X_______, ___XXXXX, XXX_____, __XXXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, ________, __XXXXXX, XXXX____, ______XX, XXXXXXX_, ________, XXXXXXXX, XX_XXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXX__XX, XXXXXXX_, ________, XXXXXXXX, XXX_XXXX, XXX_XXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, __XXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXX____, ______XX, XXXXXXXX, XXXXXXXX, XX______, ___XXXXX, XXX_____, ___XXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, ________, __XXXXXX, XXXX____, ______XX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXXX__, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXX____, _____XXX, XXXXXXXX, XXXXXXXX, XX______, ____XXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXXX____, ______XX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXXX__, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XX______, ____XXXX, XXX_____, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXXX____, ______XX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXXX__, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XX______, ____XXXX, XXX_____, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXXX____, _____XXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, X___XXXX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XX______, _____XXX, XXXX____, ________, ____XXXX, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXX_____, _____XXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, X___XXXX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, _____XXX, XXXX____, ________, ______XX, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXX_____, ____XXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, ____XXXX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXX_, ________, _XXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, _____XXX, XXXXX___, ________, ________, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XX______, ___XXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXX__, ____XXXX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  ________, ________, _XXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, _____XXX, XXXXXX__, ________, ________, __XXXXXX, XXXXXXXX, ________, __XXXXXX, X_______, __XXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, ________, ____XXXX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, _______X, XXXXX___,
  ________, ________, _XXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, _____XXX, XXXXXXXX, ________, ________, ___XXXXX, XXXXXXXX, ________, __XX____, ________, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, ________, ____XXXX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, _____XXX, XXXXXXXX, X_______, ________, ____XXXX, XXXXXXXX, ________, ________, _____XXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXX__, ____XXXX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXX_____, ________, _____XXX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, ____XXXX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXX__, ________, ______XX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, X___XXXX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XX______, _____XXX, XXXXXXXX, XXXXXXXX, ________, ______XX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, X___XXXX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XX______, ____XXXX, XXXXXXXX, XXXXXXXX, XX______, ______XX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XX______, ____XXXX, XX__XXXX, XXXXXXXX, XXXX____, _______X, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXXX__, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXX____, _____XXX, XXXXXXXX, XXXXXXXX, XX______, ____XXXX, XX__XXXX, XXXXXXXX, XXXXXX__, _______X, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXXX__, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXX____, ______XX, XXXXXXXX, XXXXXXXX, XX______, ___XXXXX, XX__XXXX, XXXXXXXX, XXXXXXX_, _______X, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXX_XXXX, XXXXX__X, XXXXXX__, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXXXXX, X_______, ___XXXXX, XX___XXX, XXXXXXXX, XXXXXXX_, _______X, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXX__X, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXXXXX, X_______, __XXXXXX, XX___XXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXX___X, XXXXXXXX, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXXXX__, _______X, XXXXXXXX, XXXXXXXX, X_______, _XXXXXXX, XX____XX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXXX, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXXXXX_, _______X, XXXXXXXX, XXXXXXXX, ________, XXXXXXXX, XX____XX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, X_______, __XXXXXX, XXXXXXXX, XXXXXXX_, __XXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXXXXXX, ________, XXXXXXXX, XXXXXXXX, _______X, XXXXXXXX, XX_____X, XXXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XX____XX, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXXX, ________, _XXXXXXX, XXXXXXXX, X_______, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XX______, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXX_____, ____XXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXX_, ________, _XXXXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XX______, _XXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XX____XX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXX_, ________, __XXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXX____, ___XXXXX, XXXXXXXX, XX______, ___XXXXX, XXXXX___, __XXXXXX, XXXXXXX_, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, _XXXXXXX, XXXXXXXX, XXXXXX__, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXX__, ________, _XXXXXXX, XXXXX___, _____XXX, XXXXXXXX, XXXXXX__, ________, XXXXXXX_, _____XXX, XXXXXXXX, XXXX____, _______X, XXXXXXXX, XXXX____, ________, XXXXX___,
  XXXXX___, ________, ____XXXX, XXXXXXXX, XXXXXX__, ______XX, XX______, _XXXXXXX, XXXXXXXX, XX___XX_, ______XX, XX______, XXXXXXXX, XXXXXX__, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, __XXXXXX, XXXXXXXX, XXXXX___, ________, ___XXXXX, 
        XXXXXXXX, XXXXX___, ________, ___XXXXX, X_______, _____XXX, XXXXXXXX, XXXXXXXX, ________, ________, ___XXXXX, XXXXXXXX, XX______, ________, _XXXXXXX, XXX_____, ________, __XXX___,
  XX______, ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, _____XXX, XXXXXXXX, XXXXXXXX, XX__XXXX, XXX_____, _____XXX, XXXXXXXX, XXX_____, ________, _______X, XXXXXXXX, XXXXXXXX, X_______, ________, ______XX, XXXXXXXX, X_______, ________, ______XX, 
        XXXXXXXX, XX______, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, XXXXXXXX, XXXXXXXX, ________, ________, ____XXXX, ________, ________, ____X___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___
};

GUI_CONST_STORAGE GUI_BITMAP bmhsp2 = {
  341, /* XSize */
  39, /* YSize */
  43, /* BytesPerLine */
  1, /* BitsPerPixel */
  achsp2,  /* Pointer to picture data (indices) */
  &Palhsp2  /* Pointer to palette */
};

/* *** End of file *** */
