/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: IconStop                                              *
* Dimensions:  14 * 19                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmIconStop;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsIconStop[] = {
#if (GUI_USE_ARGB == 0)
  0x1c1a1a/*0x3A3228*/, 0xFFFFFF
#else
  0xFF000000, 0xFFFFFFFF
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalIconStop = {
  2,  // Number of entries
  0,  // No transparency
  &_ColorsIconStop[0]
};

static GUI_CONST_STORAGE unsigned char _acIconStop[] = {
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__,
  XXXX____, __XXXX__
};

GUI_CONST_STORAGE GUI_BITMAP bmIconStop = {
  14, // xSize
  19, // ySize
  2, // BytesPerLine
  1, // BitsPerPixel
  _acIconStop,  // Pointer to picture data (indices)
  &_PalIconStop   // Pointer to palette
};

/*************************** End of file ****************************/
