/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: IconStart                                             *
* Dimensions:  17 * 19                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmIconStart;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsIconStart[] = {
#if (GUI_USE_ARGB == 0)
  0x1c1a1a/*0x3A3228*/, 0xFFFFFF
#else
  0xFF000000, 0xFFFFFFFF
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalIconStart = {
  2,  // Number of entries
  0,  // No transparency
  &_ColorsIconStart[0]
};

static GUI_CONST_STORAGE unsigned char _acIconStart[] = {
  X_______, ________, ________,
  XXX_____, ________, ________,
  XXXXX___, ________, ________,
  XXXXXX__, ________, ________,
  XXXXXXXX, ________, ________,
  XXXXXXXX, XX______, ________,
  XXXXXXXX, XXXX____, ________,
  XXXXXXXX, XXXXX___, ________,
  XXXXXXXX, XXXXXXX_, ________,
  XXXXXXXX, XXXXXXXX, ________,
  XXXXXXXX, XXXXXXX_, ________,
  XXXXXXXX, XXXXX___, ________,
  XXXXXXXX, XXX_____, ________,
  XXXXXXXX, XX______, ________,
  XXXXXXXX, ________, ________,
  XXXXXX__, ________, ________,
  XXXX____, ________, ________,
  XXX_____, ________, ________,
  X_______, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmIconStart = {
  17, // xSize
  19, // ySize
  3, // BytesPerLine
  1, // BitsPerPixel
  _acIconStart,  // Pointer to picture data (indices)
  &_PalIconStart   // Pointer to palette
};

/*************************** End of file ****************************/
