/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: IconClear                                             *
* Dimensions:  18 * 19                                               *
* NumColors:   4                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmIconClear;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsIconClear[] = {
#if (GUI_USE_ARGB == 0)
  0x1c1a1a, 0x131111, 0x090909, 0xFFFFFF
#else
// 	0xFF000000, 0xFF555555, 0xFFAAAAAA, 0xFFFFFFFF
		0xFF000000, 0xFF555555, 0xFFAAAAAA, 0xFFFFFFFF
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalIconClear = {
  4,  // Number of entries
  0,  // No transparency
  &_ColorsIconClear[0]
};

static GUI_CONST_STORAGE unsigned char _acIconClear[] = {
  0x00, 0x2F, 0xFE, 0x40, 0x00,
  0x02, 0xFF, 0xFF, 0xE0, 0x60,
  0x0B, 0xF4, 0x06, 0xFD, 0xF0,
  0x2F, 0x80, 0x00, 0x7F, 0xF0,
  0x3E, 0x00, 0x00, 0x2F, 0xF0,
  0xBC, 0x00, 0x00, 0xFF, 0xF0,
  0xF4, 0x00, 0x01, 0xFF, 0xF0,
  0xF4, 0x00, 0x00, 0x01, 0x50,
  0xA0, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0xA0,
  0x54, 0x00, 0x00, 0x01, 0xF0,
  0xFF, 0xF4, 0x00, 0x01, 0xF0,
  0xFF, 0xF0, 0x00, 0x03, 0xE0,
  0xFF, 0x80, 0x00, 0x0B, 0xC0,
  0xFF, 0xD0, 0x00, 0x2F, 0x80,
  0xF7, 0xF9, 0x01, 0xFE, 0x00,
  0x90, 0xBF, 0xFF, 0xF8, 0x00,
  0x00, 0x1B, 0xFF, 0x80, 0x00
};

GUI_CONST_STORAGE GUI_BITMAP bmIconClear = {
  18, // xSize
  19, // ySize
  5, // BytesPerLine
  2, // BitsPerPixel
  _acIconClear,  // Pointer to picture data (indices)
  &_PalIconClear   // Pointer to palette
};

/*************************** End of file ****************************/
