/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: IconAC                                                *
* Dimensions:  21 * 21                                               *
* NumColors:   4                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmIconAC;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsIconAC[] = {
#if (GUI_USE_ARGB == 0)
  0x1b1818/*0x3A3228*/, 0x555555, 0xAAAAAA, 0xFFFFFF
#else
  0xFF000000, 0xFF555555, 0xFFAAAAAA, 0xFFFFFFFF
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalIconAC = {
  4,  // Number of entries
  0,  // No transparency
  &_ColorsIconAC[0]
};

static GUI_CONST_STORAGE unsigned char _acIconAC[] = {
  0x02, 0x80, 0x07, 0x00, 0x00, 0x00,
  0x02, 0xC0, 0x07, 0x40, 0x00, 0x00,
  0x02, 0xC0, 0x07, 0x40, 0x00, 0x00,
  0x02, 0xC0, 0x07, 0x40, 0x00, 0x00,
  0x02, 0xC0, 0x07, 0x40, 0x00, 0x00,
  0x6F, 0xFF, 0xFF, 0xF8, 0x00, 0x00,
  0xFA, 0xAA, 0xAA, 0xBD, 0x00, 0x00,
  0xFA, 0xAA, 0xAA, 0xAD, 0x00, 0x00,
  0x7D, 0x55, 0x55, 0xB8, 0x00, 0x00,
  0x2D, 0x00, 0x00, 0xB0, 0x00, 0x00,
  0x1D, 0x00, 0x00, 0xB0, 0x00, 0x00,
  0x1D, 0x00, 0x00, 0xE0, 0x06, 0x80,
  0x0F, 0x00, 0x01, 0xD0, 0x2F, 0xC0,
  0x07, 0x80, 0x07, 0xC0, 0x79, 0x00,
  0x02, 0xF9, 0x6F, 0x40, 0xB0, 0x00,
  0x00, 0x7F, 0xF8, 0x00, 0xE0, 0x00,
  0x00, 0x07, 0xC0, 0x00, 0xE0, 0x00,
  0x00, 0x02, 0xD0, 0x02, 0xD0, 0x00,
  0x00, 0x01, 0xF4, 0x07, 0xC0, 0x00,
  0x00, 0x00, 0x7E, 0xBF, 0x40, 0x00,
  0x00, 0x00, 0x1B, 0xF8, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_BITMAP bmIconAC = {
  21, // xSize
  21, // ySize
  6, // BytesPerLine
  2, // BitsPerPixel
  _acIconAC,  // Pointer to picture data (indices)
  &_PalIconAC   // Pointer to palette
};

/*************************** End of file ****************************/
