/***************************************************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: limit_icon
* Dimensions:  16 * 13
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorslimit_icon[] = {
    GUI_BLACK,GUI_WHITE//0x000000,0xFFFFFF //cpp md 20130627
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Pallimit_icon = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorslimit_icon[0]
};

static GUI_CONST_STORAGE unsigned char aclimit_icon[] = {
  ________, __XXXXXX,
  ________, __X__X__,
  ________, _XX_XXX_,
  ________, _X_XXXXX,
  ________, XX______,
  ________, X_______,
  _______X, X_______,
  _______X, ________,
  ______XX, ________,
  XXXXX_X_, ________,
  _XXX_XX_, ________,
  __X__X__, ________,
  XXXXXX__, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmlimit_icon = {
  16, /* XSize */
  13, /* YSize */
  2, /* BytesPerLine */
  1, /* BitsPerPixel */
  aclimit_icon,  /* Pointer to picture data (indices) */
  &Pallimit_icon  /* Pointer to palette */
};

/* *** End of file *** */
