/***************************************************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: little_standby
* Dimensions:  100 * 36
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorslittle_standby[] = {
     0x000000,0xC8AA97
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Pallittle_standby = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorslittle_standby[0]
};

static GUI_CONST_STORAGE unsigned char aclittle_standby[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXX_____, ____XXXX, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XX______, ____XXXX, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  X_____XX, XX__XXXX, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  X____XXX, XXXXXX__, _______X, XXXX____, ___XXXXX, ___XX___, __XXXXXX, XX____XX, ____XXXX, ____XX__, __XXXX__, __XXXXXX, ________,
  X____XXX, XXXXXX__, _______X, XX______, ____XXXX, ___X____, ___XXXXX, X_______, ____XXXX, ________, ___XXXX_, ___XXXX_, ___X____,
  X_____XX, XXXXXX__, _______X, XX______, _____XXX, ________, ____XXXX, ________, ____XXXX, ________, ____XXX_, ___XXXX_, ___X____,
  XX______, _XXXXXXX, ____XXXX, XX__XXXX, X____XXX, _____XX_, ____XXXX, ____XXX_, ____XXXX, _____XXX, _____XX_, ___XXXX_, ___X____,
  XXX_____, ___XXXXX, ____XXXX, XXXXXXXX, X____XXX, ____XXXX, ____XXX_, ___XXXXX, ____XXXX, ____XXXX, X____XXX, ____XXX_, __XX____,
  XXXX____, ____XXXX, ____XXXX, XXXX____, _____XXX, ____XXXX, ____XXX_, ___XXXXX, ____XXXX, ____XXXX, X____XXX, ____XX__, __XX____,
  XXXXXX__, _____XXX, ____XXXX, XX______, _____XXX, ____XXXX, ____XXX_, ___XXXXX, ____XXXX, ____XXXX, X____XXX, ____XX__, __XX____,
  XXXXXXXX, _____XXX, ____XXXX, X_______, _____XXX, ____XXXX, ____XXX_, ___XXXXX, ____XXXX, ____XXXX, X____XXX, X____X__, __XX____,
  XXXXXXXX, X____XXX, ____XXXX, X_____XX, X____XXX, ____XXXX, ____XXX_, ___XXXXX, ____XXXX, ____XXXX, X____XXX, X____X__, _XXX____,
  XXXXXXXX, X____XXX, ____XXXX, X____XXX, X____XXX, ____XXXX, ____XXX_, ___XXXXX, ____XXXX, ____XXXX, X____XXX, XX___X__, _XXX____,
  X__XXXXX, _____XXX, ____XXXX, X____XXX, _____XXX, ____XXXX, ____XXX_, ____XXX_, ____XXXX, _____XXX, ____XXXX, XX______, _XXX____,
  X_______, ____XXXX, _______X, X_______, _____XXX, ____XXXX, ____XXXX, ________, ____XXXX, ________, ____XXXX, XX______, XXXX____,
  X_______, ___XXXXX, X______X, XX______, _____XXX, ____XXXX, ____XXXX, X_______, X___XXXX, ___X____, ___XXXXX, XXX_____, XXXX____,
  XX______, _XXXXXXX, XX_____X, XXX_____, XX___XXX, ____XXXX, ____XXXX, XX____XX, X___XXXX, ___XX___, __XXXXXX, XXX_____, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX____X, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX____X, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX____X, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX____XX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX____XX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____
};

GUI_CONST_STORAGE GUI_BITMAP bmlittle_standby = {
  100, /* XSize */
  36, /* YSize */
  13, /* BytesPerLine */
  1, /* BitsPerPixel */
  aclittle_standby,  /* Pointer to picture data (indices) */
  &Pallittle_standby  /* Pointer to palette */
};

/* *** End of file *** */
