/***************************************************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: little_model
* Dimensions:  100 * 23
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorslittle_model[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Pallittle_model = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorslittle_model[0]
};

static GUI_CONST_STORAGE unsigned char aclittle_model[] = {
  _____XXX, XXXX____, _______X, XX______, ______XX, ________, ________, ________, ________, ________, ________, ________, ________,
  ___XXXXX, XXXXXXX_, ______XX, XXX_____, ____XXXX, XX______, _XXXXXXX, X_______, _____XXX, XXXX____, ________, XXXXXXX_, ________,
  __XXXXXX, XXXXXXXX, ______XX, XXX_____, ____XXXX, XX______, XXXXXXXX, XX______, ____XXXX, XXXXX___, _______X, XXXXXXXX, X_______,
  _XXXXX__, __XXXXXX, ______XX, XXX_____, ____XXXX, XX_____X, XXXXXXXX, XXX_____, ___XXXXX, XXXXXX__, ______XX, XXXXXXXX, XX______,
  _XXXX___, ____XXXX, X_____XX, XXX_____, ____XXXX, XX____XX, XXX____X, XXXX____, __XXXXX_, __XXXXX_, _____XXX, XX___XXX, XX______,
  XXXXX___, ____XXXX, X_____XX, XXX_____, ____XXXX, XX____XX, XX______, XXXX____, __XXXX__, ___XXXXX, _____XXX, X_____XX, XXX_____,
  XXXXX___, _____XXX, X_____XX, XXX_____, ____XXXX, XX____XX, X_______, XXXX____, _XXXX___, ____XXXX, ____XXXX, _______X, XXX_____,
  XXXXX___, ______XX, ______XX, XXX_____, ____XXXX, XX______, _______X, XXXX____, _XXXX___, ____XXXX, ____XXXX, _______X, XXX_____,
  _XXXXX__, ________, ______XX, XXX_____, ____XXXX, XX______, _______X, XXX_____, _XXXX___, ____XXXX, ____XXXX, _______X, XXX_____,
  _XXXXXXX, XXXX____, ______XX, XXXXXXXX, XXXXXXXX, XX______, __XXXXXX, XX______, XXXXX___, ____XXXX, X__XXXXX, _______X, XXXX____,
  ___XXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XX______, _XXXXXXX, XX______, XXXXX___, ____XXXX, X__XXXXX, _______X, XXXX____,
  ____XXXX, XXXXXXXX, ______XX, XXXXXXXX, XXXXXXXX, XX______, _XXXXXXX, XXX_____, XXXXX___, ____XXXX, X__XXXXX, _______X, XXXX____,
  _______X, XXXXXXXX, X_____XX, XXX_____, ____XXXX, XX______, _______X, XXXX____, XXXXX___, ____XXXX, X__XXXXX, _______X, XXXX____,
  ________, __XXXXXX, XX____XX, XXX_____, ____XXXX, XX______, ________, XXXX____, XXXXX___, ____XXXX, X__XXXXX, _______X, XXXX____,
  _XX_____, ____XXXX, XX____XX, XXX_____, ____XXXX, XX______, ________, XXXXX___, _XXXX___, ____XXXX, ____XXXX, _______X, XXX_____,
  XXX_____, _____XXX, XX____XX, XXX_____, ____XXXX, XX____XX, ________, XXXXX___, _XXXX___, ____XXXX, ____XXXX, _______X, XXX_____,
  XXXX____, _____XXX, XX____XX, XXX_____, ____XXXX, XX___XXX, X_______, XXXXX___, _XXXX___, ____XXXX, ____XXXX, _______X, XXX_____,
  XXXXX___, _____XXX, XX____XX, XXX_____, ____XXXX, XX___XXX, X_______, XXXX____, _XXXX___, ____XXXX, ____XXXX, _______X, XXX_____,
  XXXXX___, ____XXXX, XX____XX, XXX_____, ____XXXX, XX___XXX, XX_____X, XXXX____, __XXXX__, ___XXXX_, _____XXX, X_____XX, XX______,
  _XXXXX__, __XXXXXX, X_____XX, XXX_____, ____XXXX, XX____XX, XXX___XX, XXXX____, __XXXXX_, __XXXXX_, ______XX, XX___XXX, XX______,
  __XXXXXX, XXXXXXXX, ______XX, XXX_____, ____XXXX, XX_____X, XXXXXXXX, XXX_____, ___XXXXX, XXXXXX__, ______XX, XXXXXXXX, X_______,
  ___XXXXX, XXXXXXX_, ______XX, XXX_____, _____XXX, XX______, XXXXXXXX, XX______, ____XXXX, XXXXX___, _______X, XXXXXXXX, ________,
  _____XXX, XXXX____, _______X, XX______, ______XX, ________, ___XXXXX, ________, ______XX, XXX_____, ________, _XXXXX__, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmlittle_model = {
  100, /* XSize */
  23, /* YSize */
  13, /* BytesPerLine */
  1, /* BitsPerPixel */
  aclittle_model,  /* Pointer to picture data (indices) */
  &Pallittle_model  /* Pointer to palette */
};

/* *** End of file *** */
