/***************************************************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: Low_limit
* Dimensions:  27 * 19
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsLow_limit[] = {
     0x000000,0xC8AA97
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalLow_limit = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsLow_limit[0]
};

static GUI_CONST_STORAGE unsigned char acLow_limit[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, X_______, __X_____,
  XXXXXXXX, XXXXXXXX, __XXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, _XXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXX_, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXX__, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXX_X, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXX__X, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXX_XX, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXX__XX, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXX_XXX, XXXXXXXX, XXX_____,
  XXXXXXXX, XXX__XXX, XXXXXXXX, XXX_____,
  XX_____X, XXX_XXXX, XXXXXXXX, XXX_____,
  XXX___XX, XX__XXXX, XXXXXXXX, XXX_____,
  XXX___XX, XX_XXXXX, XXXXXXXX, XXX_____,
  XXXX_XXX, X__XXXXX, XXXXXXXX, XXX_____,
  X_______, __XXXXXX, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____
};

GUI_CONST_STORAGE GUI_BITMAP bmLow_limit = {
  27, /* XSize */
  19, /* YSize */
  4, /* BytesPerLine */
  1, /* BitsPerPixel */
  acLow_limit,  /* Pointer to picture data (indices) */
  &PalLow_limit  /* Pointer to palette */
};

/* *** End of file *** */
