/***************************************************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: lung_logo
* Dimensions:  34 * 29
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorslung_logo[] = {
     0xFFFFFF,0xFF0000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Pallung_logo = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorslung_logo[0]
};

static GUI_CONST_STORAGE unsigned char aclung_logo[] = {
  _______X, XXX_____, XX_____X, XXX_____, ________,
  ______XX, XXXX____, XX____XX, XXXX____, ________,
  _____XXX, XXXXX___, XX___XXX, XXXXX___, ________,
  ____XXXX, XXXXX___, XX___XXX, XXXXX___, ________,
  ____XXXX, XXXXX___, XX___XXX, XXXXXX__, ________,
  ___XXXXX, XXXXX___, XX___XXX, XXXXXXX_, ________,
  ___XXXXX, XXXXX___, XX___XXX, XXXXXXX_, ________,
  __XXXXXX, XXXXXX__, XX__XXXX, XXXXXXXX, ________,
  __XXXXXX, XXXXXX_X, XXX_XXXX, XXXXXXXX, ________,
  __XXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, ________,
  _XXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, X_______,
  _XXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, X_______,
  _XXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXX___, _____XXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXX____, ______XX, XXXXXXXX, XX______,
  XXXXXXXX, XXX_____, _______X, XXXXXXXX, XX______,
  XXXXXXXX, X_______, ________, XXXXXXXX, XX______,
  XXXXXXXX, ________, ________, __XXXXXX, XX______,
  XXXXXX__, ________, ________, ____XXXX, XX______,
  _XXXX___, ________, ________, _____XXX, X_______
};

GUI_CONST_STORAGE GUI_BITMAP bmlung_logo = {
  34, /* XSize */
  29, /* YSize */
  5, /* BytesPerLine */
  1, /* BitsPerPixel */
  aclung_logo,  /* Pointer to picture data (indices) */
  &Pallung_logo  /* Pointer to palette */
};

/* *** End of file *** */
