/***************************************************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: model
* Dimensions:  182 * 37
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsmodel[] = {
     0xA05C4A,0xC9AC7B
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palmodel = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorsmodel[0]
};

static GUI_CONST_STORAGE unsigned char acmodel[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXX____, _______X, XXXXXXXX, XXXXXXXX, ________, ___XXXXX, XXXXXXXX, XXX_____, ______XX, XXXXXXXX, XXX_____, ________, ____XXXX, XXXXXXXX, X_______, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXX__,
  XXXXXXXX, XXXX____, _______X, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXXXXX, XXX_____, ______XX, XXXXXXXX, X_______, ________, _____XXX, XXXXXXXX, X_______, ________, ________, __XXXXXX, XXXXXXXX, XXXXXX__, ________, _XXXXX__,
  XXXXXXXX, XXXX____, _______X, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXXXXX, XX______, ______XX, XXXXXXXX, ________, ________, _______X, XXXXXXXX, X_______, ________, ________, __XXXXXX, XXXXXXXX, XXXXXX__, ________, _XXXXX__,
  XXXXXXXX, XXX_____, ________, XXXXXXXX, XXXXXXXX, ________, _____XXX, XXXXXXXX, XX______, ______XX, XXXXXXX_, ________, ________, ________, XXXXXXXX, X_______, ________, ________, __XXXXXX, XXXXXXXX, XXXXX___, ________, _XXXXX__,
  XXXXXXXX, XXX_____, ________, XXXXXXXX, XXXXXXXX, ________, _____XXX, XXXXXXXX, X_______, ______XX, XXXXXX__, ________, ________, ________, XXXXXXXX, X_______, ________, ________, __XXXXXX, XXXXXXXX, XXXX____, ________, _XXXXX__,
  XXXXXXXX, XXX_____, ________, XXXXXXXX, XXXXXXXX, ________, ______XX, XXXXXXXX, X_______, ______XX, XXXXXX__, ________, XXXXXX__, ________, _XXXXXXX, X_______, ________, ________, __XXXXXX, XXXXXXXX, XXX_____, ________, _XXXXX__,
  XXXXXXXX, XX______, ________, _XXXXXXX, XXXXXXXX, ________, ______XX, XXXXXXXX, ________, ______XX, XXXXX___, _______X, XXXXXXX_, ________, _XXXXXXX, X_______, ________, ________, __XXXXXX, XXXXXXXX, XXX_____, ________, _XXXXX__,
  XXXXXXXX, XX______, ________, _XXXXXXX, XXXXXXXX, ________, _______X, XXXXXXXX, ________, ______XX, XXXXX___, ______XX, XXXXXXXX, ________, _XXXXXXX, X_______, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, _XXXXX__,
  XXXXXXXX, X_______, ________, __XXXXXX, XXXXXXXX, ________, _______X, XXXXXXXX, ________, ______XX, XXXXX___, ______XX, XXXXXXXX, ________, _XXXXXXX, X_______, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X______X, ________, _XXXXX__,
  XXXXXXXX, X_______, ________, __XXXXXX, XXXXXXXX, ________, _______X, XXXXXXX_, ________, ______XX, XXXXX___, ______XX, XXXXXXXX, ________, _XXXXXXX, X_______, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _______X, ________, _XXXXX__,
  XXXXXXXX, X_______, ________, __XXXXXX, XXXXXXXX, ________, ________, XXXXXXX_, ________, ______XX, XXXXX___, _______X, XXXXXXXX, ________, _XXXXXXX, X_______, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ______XX, ________, _XXXXX__,
  XXXXXXXX, ________, _X______, ___XXXXX, XXXXXXXX, ________, ________, XXXXXX__, ________, ______XX, XXXXX___, ________, XXXXXXXX, ________, XXXXXXXX, X_______, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, _____XXX, ________, _XXXXX__,
  XXXXXXXX, ________, _X______, ___XXXXX, XXXXXXXX, ________, ________, _XXXXX__, ________, ______XX, XXXXXX__, ________, __XXXXX_, _______X, XXXXXXXX, X_______, ________, __XXXXXX, XXXXXXXX, XXXXXX__, ____XXXX, ________, _XXXXX__,
  XXXXXXXX, ________, _X______, ___XXXXX, XXXXXXXX, ________, _X______, _XXXX___, ____X___, ______XX, XXXXXX__, ________, _____X__, ______XX, XXXXXXXX, X_______, ________, _____XXX, XXXXXXXX, XXXXX___, ____XXXX, ________, _XXXXX__,
  XXXXXXX_, ________, XXX_____, ____XXXX, XXXXXXXX, ________, _X______, __XXX___, ____X___, ______XX, XXXXXXX_, ________, ________, _____XXX, XXXXXXXX, X_______, ________, _______X, XXXXXXXX, XXXXX___, ___XXXXX, ________, _XXXXX__,
  XXXXXXX_, ________, XXX_____, ____XXXX, XXXXXXXX, ________, _XX_____, __XX____, ___XX___, ______XX, XXXXXXXX, ________, ________, ___XXXXX, XXXXXXXX, X_______, ________, ________, XXXXXXXX, XXXX____, __XXXXXX, ________, _XXXXX__,
  XXXXXXX_, ________, XXX_____, ____XXXX, XXXXXXXX, ________, _XX_____, ___X____, ___XX___, ______XX, XXXXXXXX, XX______, ________, ____XXXX, XXXXXXXX, X_______, ________, ________, _XXXXXXX, XXX_____, _XXXXXXX, ________, _XXXXX__,
  XXXXXX__, _______X, XXXX____, _____XXX, XXXXXXXX, ________, _XXX____, ________, __XXX___, ______XX, XXXXXXXX, XXX_____, ________, ______XX, XXXXXXXX, X_______, ________, ________, __XXXXXX, XX______, _XXXXXXX, ________, _XXXXX__,
  XXXXXX__, _______X, XXXX____, _____XXX, XXXXXXXX, ________, _XXX____, ________, __XXX___, ______XX, XXXXXXXX, X_______, ________, _______X, XXXXXXXX, X____XXX, XXXXXX__, ________, __XXXXXX, XX______, XXXXXXXX, ________, _XXXXX__,
  XXXXXX__, _______X, XXXX____, _____XXX, XXXXXXXX, ________, _XXX____, ________, __XXX___, ______XX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ___XXXXX, X______X, XXXXXXXX, ________, _XXXXX__,
  XXXXX___, ______XX, XXXXX___, ______XX, XXXXXXXX, ________, _XXXX___, ________, _XXXX___, ______XX, XXXXXX__, _______X, XXX_____, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ___XXXXX, ______XX, XXXXXXXX, ________, _XXXXX__,
  XXXXX___, ________, ________, ______XX, XXXXXXXX, ________, _XXXX___, ________, _XXXX___, ______XX, XXXXX___, ______XX, XXXXX___, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ___XXXXX, ________, ________, ________, ________,
  XXXX____, ________, ________, _______X, XXXXXXXX, ________, _XXXXX__, ________, XXXXX___, ______XX, XXXXX___, _____XXX, XXXXXXX_, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XX______, ___XXXXX, ________, ________, ________, ________,
  XXXX____, ________, ________, _______X, XXXXXXXX, ________, _XXXXX__, ________, XXXXX___, ______XX, XXXX____, _____XXX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XX______, ___XXXXX, ________, ________, ________, ________,
  XXXX____, ________, ________, _______X, XXXXXXXX, ________, _XXXXXX_, _______X, XXXXX___, ______XX, XXXX____, _____XXX, XXXXXXXX, X_______, __XXXXXX, XXXXXXXX, XXXXXXXX, XX______, ___XXXXX, ________, ________, ________, ________,
  XXX_____, ________, ________, ________, XXXXXXXX, ________, _XXXXXX_, _______X, XXXXX___, ______XX, XXXX____, _____XXX, XXXXXXXX, X_______, __XXXXXX, XXXXXXXX, XXXXXXXX, XX______, ___XXXXX, ________, ________, ________, ________,
  XXX_____, ________, ________, ________, XXXXXXXX, ________, _XXXXXXX, ______XX, XXXXX___, ______XX, XXXX____, _____XXX, XXXXXXXX, X_______, __XXXXXX, __XXXXXX, XXXXXXXX, X_______, ___XXXXX, ________, ________, ________, ________,
  XXX_____, ____XXXX, XXXXXXX_, ________, XXXXXXXX, ________, _XXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXX____, ______XX, XXXXXXXX, X_______, __XXXXXX, ____XXXX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, ________, _XXXXX__,
  XX______, ____XXXX, XXXXXXX_, ________, _XXXXXXX, ________, _XXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXX____, _______X, XXXXXXXX, ________, _XXXXXXX, _______X, XXXXXX__, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, ________, _XXXXX__,
  XX______, ___XXXXX, XXXXXXXX, ________, _XXXXXXX, ________, _XXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXX___, ________, XXXXXX__, ________, _XXXXXXX, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, ________, _XXXXX__,
  XX______, ___XXXXX, XXXXXXXX, ________, _XXXXXXX, ________, _XXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXX___, ________, ________, ________, XXXXXXXX, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, ________, _XXXXX__,
  X_______, ___XXXXX, XXXXXXXX, ________, __XXXXXX, ________, _XXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXX__, ________, ________, ________, XXXXXXXX, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, _XXXXX__,
  X_______, __XXXXXX, XXXXXXXX, X_______, __XXXXXX, ________, _XXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXX_, ________, ________, _______X, XXXXXXXX, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, _XXXXX__,
  X_______, __XXXXXX, XXXXXXXX, X_______, __XXXXXX, ________, _XXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, ________, ________, _____XXX, XXXXXXXX, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, _XXXXX__,
  ________, __XXXXXX, XXXXXXXX, X_______, ___XXXXX, ________, _XXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XX______, ________, ___XXXXX, XXXXXXXX, XX______, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, _XXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__
};

GUI_CONST_STORAGE GUI_BITMAP bmmodel = {
  182, /* XSize */
  37, /* YSize */
  23, /* BytesPerLine */
  1, /* BitsPerPixel */
  acmodel,  /* Pointer to picture data (indices) */
  &Palmodel  /* Pointer to palette */
};

/* *** End of file *** */
