/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: NESCO_LOGO                                            *
* Dimensions:  340 * 71                                              *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmNESCO_LOGO;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsNESCO_LOGO[] = {
  0x000000, 0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalNESCO_LOGO = {
  2,  // Number of entries
  1,  // Has transparency
  &_ColorsNESCO_LOGO[0]
};

static GUI_CONST_STORAGE unsigned char _acNESCO_LOGO[] = {
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXX___, ________, ________, ________, ________, __XXXXXX, XXXXX___, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, ________, ________, ________, ________, XXXXXXXX, XXXXXXX_, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XX______, ________, ________, _______X, XXXX____, ____XXXX, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ______XX, XX______, ______XX, X_______,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, _____XXX, XXXXXXXX, XXX____X, XX______,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ____XXX_, XXXXXXXX, XXXX____, XXX_____,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ____XXX_, __XXXX__, XXXXX___, _XX_____,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ____XX__, __XXXX__, _XXXX___, _XXX____,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ___XXX__, __XXXX__, _XXXX___, __XX____,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ___XX___, __XXXX__, _XXXX___, __XX____,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ___XX___, __XXXX_X, XXXXX___, __XX____,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ___XX___, __XXXXXX, XXX_____, __XX____,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ___XX___, __XXXXXX, XX______, __XX____,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ___XX___, __XXXX_X, XXX_____, __XX____,
  XXXXXX__, ________, ________, ________, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ____XXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, 
        ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ___XXX__, __XXXX_X, XXXX____, __XX____,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ____XX__, __XXXX__, XXXXX___, _XXX____,
  XXXXXXXX, XX______, ________, ________, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, _____XXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ____XXX_, __XXXX__, _XXXX___, _XX_____,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, __XXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ___XXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ____XXX_, XXXXXXXX, __XXXXX_, XXX_____,
  XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ___XXXXX, XXXXXXXX, XXXXXX__, _______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, _____XXX, XXXXXXXX, ___XXXXX, XX______,
  XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXXX___, ________, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ______XX, XX______, ______XX, XX______,
  XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _______X, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, __XXXXXX, XXXXXXXX, XXXXX___, ________, _XXXXXXX, XXXXXXXX, XXXXXX__, ________, _______X, XXX_____, ____XXXX, X_______,
  XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ______XX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, __XXXXXX, XXXXXXXX, XXXX____, ________, __XXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, XXXXXXXX, XXXXXXX_, ________,
  XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, X_______, XXXXXXXX, XXXXXXXX, ________, _____XXX, XXXXXXXX, 
        XXXXXXXX, XXXXX___, ___XXXXX, XXXXXXXX, XXXXXXXX, XX______, __XXXXXX, XXXXXXXX, XXXX____, ________, ___XXXXX, XXXXXXXX, XXXXXXX_, ________, ________, __XXXXXX, XXXXX___, ________,
  XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXX__, ________, ___XXXXX, XXXXXXXX, X_______, ____XXXX, XXXXXXXX, 
        XXXXXXXX, X_______, ______XX, XXXXXXXX, XXXXXXXX, XXX_____, __XXXXXX, XXXXXXXX, XXXX____, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ______XX, X_______, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, XXXXXXXX, XXXX____, ________, _____XXX, XXXXXXXX, X_______, ____XXXX, XXXXXXXX, 
        XXXXXXX_, ________, ________, XXXXXXXX, XXXXXXXX, XXX_____, __XXXXXX, XXXXXXXX, XXXX____, ________, ____XXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, XXXXXXXX, XXX_____, ________, ______XX, XXXXXXXX, X_______, ____XXXX, XXXXXXXX, 
        XXXXXX__, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XXXX____, ________, _____XXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, _______X, XXXXXXXX, XX______, ________, ______XX, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, 
        XXXXXX__, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XXXXX___, ________, _____XXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, _______X, XXXXXXXX, XX______, ________, _______X, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XXXXX___, ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, _______X, XXXXXXXX, XX______, ________, _______X, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, __XXXXXX, XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XXXXX___, ________, ______XX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, _______X, XXXXXXXX, XX______, ________, _______X, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, __XXXXXX, XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XXXXXX__, ________, _______X, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, _______X, XXXXXXXX, XX______, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, __XXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXX_, ________, ________, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, _______X, XXXXXXXX, XXX_____, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, __XXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXX_, ________, ________, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXX_____, ________, _______X, XXXXXXXX, XXXX____, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, ________, ________, _XXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, XXXXXXXX, XXXXX___, ________, ________, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, X_______, ________, _XXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, _______X, XXXXXXXX, XXXXXX__, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, X_______, ________, __XXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXXXX, XXXXXXX_, ________, ________, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XX______, ________, ___XXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXXXX, XXXXXXXX, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, XXXXXXXX, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXX_____, ________, ____XXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, XXXXXXXX, X_______, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXX____, ________, ____XXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXX____, ________, _____XXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________,
  XXXXXXXX, XXX__XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________,
  XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXX___, ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________,
  XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXX__, ________, _______X, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________,
  XXXXXXXX, XXX_____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXX_, ________, _______X, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________,
  XXXXXXXX, XXX_____, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXX_, ________, ________, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________,
  XXXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XX______, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________,
  XXXXXXXX, XXX_____, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXX_____, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, ________, ________, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXX_____, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, X_______, ________, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXX_____, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XX______, ________, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, _______X, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ________, ______XX, XXXXXXXX, XXX_____, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XX______, ________, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________, XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXX_____, ________, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXX_____, ________, ________, ________, ________, ________, ________, XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ___XXXXX, XXXXXXXX, XXXXX___, ________, _______X, XXXXXXXX, XXXXXXXX, XXXX____, _______X, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ______XX, XXXXXXXX, X_______, ________, ________, _XXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ___XXXXX, XXXXXXXX, XXXXX___, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ______XX, XXXXXXXX, X_______, ________, ________, _XXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ___XXXXX, XXXXXXXX, XXXXX___, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXX__, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ______XX, XXXXXXXX, X_______, ________, ________, _XXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ___XXXXX, XXXXXXXX, XXXXX___, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ______XX, XXXXXXXX, X_______, ________, ________, _XXXXXXX, XXX_____, ___XXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, ___XXXXX, XXXXXXXX, XXXXX___, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ______XX, XXXXXXXX, X_______, ________, ________, XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX, 
        XXXXX___, ________, ________, __XXXXXX, XXXXXXXX, XXXXX___, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, _______X, XXXXXXXX, XX______, ________, ________, XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX, 
        XXXXXX__, ________, ________, __XXXXXX, XXXXXXXX, XXXXX___, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, _______X, XXXXXXXX, XXX_____, ________, _______X, XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX, 
        XXXXXX__, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, _______X, XXXXXXXX, XXXX____, ________, ______XX, XXXXXXXX, XX______, ____XXXX, XXXXXXXX, 
        XXXXXXX_, ________, ________, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXX__, ________, ____XXXX, XXXXXXXX, XX______, ____XXXX, XXXXXXXX, 
        XXXXXXXX, X_______, _______X, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, XXXXXXXX, XXXXXXXX, X_______, _XXXXXXX, XXXXXXXX, X_______, _____XXX, XXXXXXXX, 
        XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, _____XXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ______XX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _______X, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, _______X, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, _XXXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, __XXXXXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, __XXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, _____XXX, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, ____XXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, _______X, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, _____XXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, _____XXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, 
        ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmNESCO_LOGO = {
  340, // xSize
  71, // ySize
  43, // BytesPerLine
  1, // BitsPerPixel
  _acNESCO_LOGO,  // Pointer to picture data (indices)
  &_PalNESCO_LOGO   // Pointer to palette
};

/*************************** End of file ****************************/
