/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert-Demo V5.26.                            *
*        Compiled Aug  8 2014, 14:40:24                              *
*                                                                    *
*        (c) 2002-2014  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2014  Segger Microcontroller GmbH & Co. KG         *
*        www.segger.com                                              *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: New_Siriusmed                                         *
* Dimensions:  386 * 35                                              *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmNew_Siriusmed;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsNew_Siriusmed[] = {
  0x000000, 0xAC5A00
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalNew_Siriusmed = {
  2,  // Number of entries
  1,  // No transparency
  &_ColorsNew_Siriusmed[0]
};

static GUI_CONST_STORAGE unsigned char _acNew_Siriusmed[] = {
   ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, 
        ________, ________, _XXXXXXX, XXXX____, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XX______, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXX____, _____XXX, XXXXXXXX, XXXXX___, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________,
  ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXX___, ___XXXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXX__, __XXXXXX, XXXXXXXX, XXXXX___, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXX_, __XXXXXX, XXXXXXXX, XXXXX___, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, XXXXXXXX, XXX_____, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ________, XXXXXXXX, XXXXX___, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX____X, XXXXXXXX, XXXXXXXX, ________, ________, ________, ______XX, 
        XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXX___, __XXXXXX, XXXXXXXX, XX______, ________, ________, XXXXXXXX, XXXXXXXX, ________, XXXXXXXX, XXX_____,
  _XXXXXXX, XXXXXXXX, X_______, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ________, ___XXXXX, XXXXXX__, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX____X, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXX_____,
  _XXXXXXX, XXXXXXXX, ________, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ________, ____XXXX, XXXXXX__, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX___XX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, 
        _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ___XXXXX, XXXX____,
  XXXXXXXX, XXXXXXX_, ________, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ________, _____XXX, XXXXXXX_, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX___XX, XXXXXXXX, XXXX____, ________, ________, ________, ________, 
        __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ___XXXXX, XXXX____,
  XXXXXXXX, XXXXXXX_, ________, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ________, _____XXX, XXXXXXX_, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX___XX, XXXXXXXX, XXXX____, ________, ________, ________, XXXXXX__, 
        ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ________, ____XXXX, XXXXXXX_, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX___XX, XXXXXXXX, XXXXX___, ________, ________, ________, XXXXXXX_, 
        ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX___XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXXXX, 
        _____XXX, XXXXXXXX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX___XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, 
        X_____XX, XXXXXXXX, XX_XXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, 
        X______X, XXXXXXXX, X__XXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, 
        X_______, XXXXXXXX, X__XXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, 
        X_______, _XXXXXXX, ___XXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  ________, ________, ________, _____XXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, X_______, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, ________, ________, ________, __XXXXXX, XXXX____, XXXXXXXX, 
        X_______, __XXXXX_, ___XXXXX, XXXXX___, XXXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  ________, ________, ________, ______XX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, XX______, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, ________, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, 
        X_______, ___XXX__, ___XXXXX, XXXXX___, XXXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  ________, ________, ________, ______XX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, XX______, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, ________, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, XXXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ___XXXXX, XXXXX___,
  ________, ________, ________, _____XXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XXX_____, __XXXXXX, XXX____X, XXXXXXXX, XXXXXX__, ________, __XXXXXX, XXX_____, ________, ________, ________, __XXXXXX, XXXX____, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, XXXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ___XXXXX, XXXXX___,
  ________, ________, ________, ____XXXX, XXXXXX__, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XXX_____, __XXXXXX, XXX____X, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, XX______, ________, ________, ________, _XXXXXXX, XXX_____, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XXXX____, __XXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, XX______, ________, ________, XXXXXXXX, XXXXXXXX, ________, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ______XX, XXXXXXXX, XXXX____, __XXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ______XX, XXXXXXXX, XXXXX___, __XXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, _______X, XXXXXXXX, XXXXX___, __XXXXXX, XXX_____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, _______X, XXXXXXXX, XXXXXX__, __XXXXXX, XXX_____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ________, XXXXXXXX, XXXXXX__, __XXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XXXXX___, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmNew_Siriusmed_Blue = {
  309, /* XSize */
  28, /* YSize */
  39, /* BytesPerLine */
  1, /* BitsPerPixel */
  _acNew_Siriusmed,  // Pointer to picture data (indices)
  &_PalNew_Siriusmed   // Pointer to palette
};

/*************************** End of file ****************************/
