/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: New_Siriusmed
* Dimensions:  309 * 28
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsNew_Siriusmed[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalNew_Siriusmed = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &ColorsNew_Siriusmed[0]
};

static GUI_CONST_STORAGE GUI_COLOR ColorsNew_Siriusmed_GA[] = {
     0xF7F7F7,0x7F3000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalNew_Siriusmed_GA = {
  2,	/* number of entries */
  0, 	/* Has transparency */
  &ColorsNew_Siriusmed_GA[0]
};


static GUI_CONST_STORAGE unsigned char acNew_Siriusmed[] = {
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, 
        ________, ________, _XXXXXXX, XXXX____, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XX______, ______XX, XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXX____, _____XXX, XXXXXXXX, XXXXX___, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________,
  ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXX___, ___XXXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXX__, __XXXXXX, XXXXXXXX, XXXXX___, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXX_, __XXXXXX, XXXXXXXX, XXXXX___, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, XXXXXXXX, XXX_____, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ________, XXXXXXXX, XXXXX___, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX____X, XXXXXXXX, XXXXXXXX, ________, ________, ________, ______XX, 
        XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXX___, __XXXXXX, XXXXXXXX, XX______, ________, ________, XXXXXXXX, XXXXXXXX, ________, XXXXXXXX, XXX_____,
  _XXXXXXX, XXXXXXXX, X_______, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ________, ___XXXXX, XXXXXX__, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX____X, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, 
        XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXX_____,
  _XXXXXXX, XXXXXXXX, ________, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ________, ____XXXX, XXXXXX__, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX___XX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, 
        _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ___XXXXX, XXXX____,
  XXXXXXXX, XXXXXXX_, ________, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ________, _____XXX, XXXXXXX_, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX___XX, XXXXXXXX, XXXX____, ________, ________, ________, ________, 
        __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ___XXXXX, XXXX____,
  XXXXXXXX, XXXXXXX_, ________, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ________, _____XXX, XXXXXXX_, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX___XX, XXXXXXXX, XXXX____, ________, ________, ________, XXXXXX__, 
        ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ________, ____XXXX, XXXXXXX_, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX___XX, XXXXXXXX, XXXXX___, ________, ________, ________, XXXXXXX_, 
        ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX___XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXXXX, 
        _____XXX, XXXXXXXX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX___XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, 
        X_____XX, XXXXXXXX, XX_XXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, 
        X______X, XXXXXXXX, X__XXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, 
        X_______, XXXXXXXX, X__XXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, 
        X_______, _XXXXXXX, ___XXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  ________, ________, ________, _____XXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, X_______, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, ________, ________, ________, __XXXXXX, XXXX____, XXXXXXXX, 
        X_______, __XXXXX_, ___XXXXX, XXXXX___, XXXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  ________, ________, ________, ______XX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, XX______, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, ________, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, 
        X_______, ___XXX__, ___XXXXX, XXXXX___, XXXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXX___,
  ________, ________, ________, ______XX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, XX______, __XXXXXX, XXX____X, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXX_____, ________, ________, ________, ___XXXXX, XXXX____, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, XXXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ___XXXXX, XXXXX___,
  ________, ________, ________, _____XXX, XXXXXXX_, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XXX_____, __XXXXXX, XXX____X, XXXXXXXX, XXXXXX__, ________, __XXXXXX, XXX_____, ________, ________, ________, __XXXXXX, XXXX____, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, XXXXXXXX, XXXXXXX_, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, ___XXXXX, XXXXX___,
  ________, ________, ________, ____XXXX, XXXXXX__, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XXX_____, __XXXXXX, XXX____X, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, XX______, ________, ________, ________, _XXXXXXX, XXX_____, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XXXX____, __XXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, XX______, ________, ________, XXXXXXXX, XXXXXXXX, ________, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ______XX, XXXXXXXX, XXXX____, __XXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ______XX, XXXXXXXX, XXXXX___, __XXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, _______X, XXXXXXXX, XXXXX___, __XXXXXX, XXX_____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, _______X, XXXXXXXX, XXXXXX__, __XXXXXX, XXX_____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXX__, ________, XXXXXXXX, XXXXXX__, __XXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XXXXX___, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, XXXXXXXX, 
        X_______, ________, ___XXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmNew_Siriusmed = {
  309, /* XSize */
  28, /* YSize */
  39, /* BytesPerLine */
  1, /* BitsPerPixel */
  acNew_Siriusmed,  /* Pointer to picture data (indices) */
  &PalNew_Siriusmed  /* Pointer to palette */
};

GUI_CONST_STORAGE GUI_BITMAP bmNew_Siriusmed_GA = {
  309, /* XSize */
  28, /* YSize */
  39, /* BytesPerLine */
  1, /* BitsPerPixel */
  acNew_Siriusmed,  /* Pointer to picture data (indices) */
  &PalNew_Siriusmed_GA  /* Pointer to palette */
};

/* *** End of file *** */
