/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: Plug_WB_Icon
* Dimensions:  28 * 16
* NumColors:   4
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsPlug_WB_Icon[] = {
     0x420000,0x725d50,0xa99487,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalPlug_WB_Icon = {
  4,	/* number of entries */
  0, 	/* No transparency */
  &ColorsPlug_WB_Icon[0]
};

static GUI_CONST_STORAGE unsigned char acPlug_WB_Icon[] = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x1F, 0xFF, 0xE9, 0x00, 0x00,
  0x00, 0x00, 0x7F, 0xFF, 0x85, 0x00, 0x00,
  0x00, 0x01, 0xFF, 0xFF, 0x4F, 0xFF, 0xE0,
  0x00, 0x02, 0xFF, 0xFF, 0x4F, 0xFF, 0xE4,
  0x15, 0x5B, 0xFF, 0xFF, 0x45, 0x55, 0x50,
  0x3F, 0xFF, 0xFF, 0xFF, 0x40, 0x00, 0x00,
  0x3F, 0xFF, 0xFF, 0xFF, 0x45, 0x00, 0x00,
  0x3F, 0xFF, 0xFF, 0xFF, 0x45, 0x00, 0x00,
  0x3F, 0xFF, 0xFF, 0xFF, 0x45, 0x00, 0x00,
  0x15, 0x5B, 0xFF, 0xFF, 0x4F, 0xFF, 0xE0,
  0x00, 0x02, 0xFF, 0xFF, 0x4F, 0xFF, 0xE4,
  0x00, 0x01, 0xFF, 0xFF, 0x45, 0x55, 0x50,
  0x00, 0x00, 0x7F, 0xFF, 0x80, 0x00, 0x00,
  0x00, 0x00, 0x1F, 0xFF, 0xE9, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_BITMAP bmPlug_WB_Icon = {
  28, /* XSize */
  16, /* YSize */
  7, /* BytesPerLine */
  2, /* BitsPerPixel */
  acPlug_WB_Icon,  /* Pointer to picture data (indices) */
  &PalPlug_WB_Icon  /* Pointer to palette */
};

/* *** End of file *** */
