/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: RN5NO_Icon                                            *
* Dimensions:  216 * 29                                              *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmRN5NO_Icon;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsRN5NO_Icon[] = {
  0x000000, 0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalRN5NO_Icon = {
  2,  // Number of entries
  1,  // Has transparency
  &_ColorsRN5NO_Icon[0]
};

static GUI_CONST_STORAGE unsigned char _acRN5NO_Icon[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX____XX, XXXXXXXX, ________, ________, _XXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXX_, ________, ______XX, XXXXXX__, ___XXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, X_______, ________, _XXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, ________, ______XX, XXXXXX__, __XXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XX______, ________, _XXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, X_______, ______XX, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXX_____, ________, _XXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, XX______, ______XX, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXXX____, ________, _XXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXX_____, ______XX, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXX___, ________, _XXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXX____, ______XX, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXX__, ________, _XXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX____XX, XXXXXXXX, XXXXX___, ______XX, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX______, ________, _XXXXXXX, XXXX__XX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, XX______, ________, ________, ____XXXX, XXXXXX__, ________, ________, ________, ______XX, XXXXXXXX, XXXXXX__, ______XX, XXXXXX__, _XXXXXXX, XXX_____, ________, 
        ______XX, XXXXXXXX,
  XXXXXXXX, X_______, ________, __XXXXXX, XXXX__XX, XXXXXXXX, XXXXXXXX, ________, _XXXXXXX, XX______, ________, ________, ____XXXX, XXXXXX__, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXX__, _XXXXXXX, XX______, ________, 
        _______X, XXXXXXXX,
  XXXXXXXX, X_______, ________, ___XXXXX, XXXX__XX, XXXXXXXX, XXXXXXXX, X_______, _XXXXXXX, XX______, ________, ________, ____XXXX, XXXXXX__, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXX__, _XXXXXXX, XX______, ________, 
        _______X, XXXXXXXX,
  XXXXXXXX, X_______, ________, ___XXXXX, XXXX__XX, XXXXXXXX, XXXXXXXX, XX______, _XXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XX____XX, XXXXXX__, _XXXXXXX, XX______, ________, 
        _______X, XXXXXXXX,
  XXXXXXXX, X_______, ________, ___XXXXX, XXXX__XX, XXXXXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX____XX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXX__, _XXXXXXX, XX______, ________, 
        _______X, XXXXXXXX,
  XXXXXXXX, X_______, ________, __XXXXXX, XXXX__XX, XXXXXXX_, XXXXXXXX, XXXX____, _XXXXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXX__, _XXXXXXX, XX______, ________, 
        _______X, XXXXXXXX,
  XXXXXXXX, X_______, ________, _XXXXXXX, XXXX__XX, XXXXXXX_, _XXXXXXX, XXXXX___, _XXXXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXX__, _XXXXXXX, XX______, ________, 
        _______X, XXXXXXXX,
  XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXX_, __XXXXXX, XXXXXX__, _XXXXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXX__, __XXXXXX, XXXXXXXX, XXXXXX__, _XXXXXXX, XX______, ________, 
        _______X, XXXXXXXX,
  XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXX_, ___XXXXX, XXXXXXX_, _XXXXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXX__, ___XXXXX, XXXXXXXX, XXXXXX__, _XXXXXXX, XX______, ________, 
        _______X, XXXXXXXX,
  XXXXXXXX, X_______, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXX_, ____XXXX, XXXXXXXX, _XXXXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXX__, ____XXXX, XXXXXXXX, XXXXXX__, _XXXXXXX, XX______, ________, 
        _______X, XXXXXXXX,
  XXXXXXXX, X_______, _XXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXX___XX, XXXXXX__, _____XXX, XXXXXXXX, XXXXXX__, _XXXXXXX, XX______, ________, 
        _______X, XXXXXXXX,
  XXXXXXXX, X_______, _XXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXX___XX, XXXXXX__, ______XX, XXXXXXXX, XXXXXX__, _XXXXXXX, XX______, ________, 
        ______XX, XXXXXXXX,
  XXXXXXXX, X_______, __XXXXXX, XXXXXXXX, XXX___XX, XXXXXXX_, _______X, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________, XXXXXXXX, XXX___XX, XXXXXX__, _______X, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX,
  XXXXXXXX, X_______, ___XXXXX, XXXXXXXX, XX____XX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXX__, ________, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX,
  XXXXXXXX, X_______, ____XXXX, XXXXXXXX, X_____XX, XXXXXXX_, ________, _XXXXXXX, XXXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXX__, ________, _XXXXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX,
  XXXXXXXX, X_______, _____XXX, XXXXXXXX, X_____XX, XXXXXXX_, ________, __XXXXXX, XXXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXX__, ________, __XXXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX,
  XXXXXXXX, X_______, ______XX, XXXXXXXX, X_____XX, XXXXXXX_, ________, ___XXXXX, XXXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXX__, ________, ___XXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX,
  XXXXXXXX, X_______, ______XX, XXXXXXXX, XX____XX, XXXXXXX_, ________, ____XXXX, XXXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX____XX, XXXXXX__, ________, ____XXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXXXX,
  XXXXXXXX, X_______, _______X, XXXXXXXX, XXX___XX, XXXXXXX_, ________, _____XXX, XXXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXX__, ________, ______XX, XXXXXX__, __XXXXXX, XXXXXXXX, XXXXXXXX, 
        XXXXXXXX, XXXXXX__,
  XXXXXXXX, X_______, ________, XXXXXXXX, XXXX__XX, XXXXXXX_, ________, ______XX, XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________,
  XXXXXXXX, X_______, ________, _XXXXXXX, XXXXXXXX, XXXXXXX_, ________, _______X, XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________,
  XXXXXXXX, X_______, ________, _XXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, 
        ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmRN5NO_Icon = {
  216, // xSize
  29, // ySize
  27, // BytesPerLine
  1, // BitsPerPixel
  _acRN5NO_Icon,  // Pointer to picture data (indices)
  &_PalRN5NO_Icon   // Pointer to palette
};

/*************************** End of file ****************************/
