/***************************************************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: silence_icon
* Dimensions:  33 * 34
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorssilence_icon[] = {
     0x000000,0x0000FF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palsilence_icon = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorssilence_icon[0]
};

static GUI_CONST_STORAGE unsigned char acsilence_icon[] = {
  ________, ______XX, XXX_____, ________, ________,
  ________, _____XXX, XXXX____, ________, ________,
  ________, ____XXXX, XXXXX___, ________, ________,
  _X______, ___XX___, ____XX__, _______X, ________,
  _XX_____, __XX____, _____XX_, ______XX, ________,
  __XX____, _XX_____, ______XX, _____XX_, ________,
  ___XX___, XX______, _______X, X___XX__, ________,
  ____XX_X, X_______, ________, XX_XX___, ________,
  _____XXX, X_______, ________, XXXX____, ________,
  ______XX, ________, ________, _XX_____, ________,
  ______XX, X_______, ________, XXX_____, ________,
  ______X_, XX______, _______X, X_X_____, ________,
  _____XX_, _XX_____, ______XX, __XX____, ________,
  _____XX_, __XX____, _____XX_, __XX____, ________,
  _____XX_, ___XX___, ____XX__, __XX____, ________,
  _____XX_, ____XX__, ___XX___, __XX____, ________,
  _____XX_, _____XX_, __XX____, __XX____, ________,
  _____XX_, ______XX, _XX_____, __XX____, ________,
  ____XX__, _______X, XX______, ___XX___, ________,
  ____XX__, _______X, XX______, ___XX___, ________,
  ____X___, ______XX, _XX_____, ____X___, ________,
  ___XX___, _____XX_, __XX____, ____XX__, ________,
  ___XX___, ____XX__, ___XX___, ____XX__, ________,
  __XX____, ___XX___, ____XX__, _____XX_, ________,
  _XX_____, __XX____, _____XX_, ______XX, ________,
  XX______, _XX_____, ______XX, _______X, X_______,
  XX______, XX______, _______X, X______X, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  ______XX, ____XXXX, XXXXX___, _XX_____, ________,
  _____XX_, _____XXX, XXXX____, __XX____, ________,
  ____XX__, ______XX, XXX_____, ___XX___, ________,
  ___XX___, ________, ________, ____XX__, ________,
  __XX____, ________, ________, _____XX_, ________,
  _XX_____, ________, ________, ______XX, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmsilence_icon = {
  33, /* XSize */
  34, /* YSize */
  5, /* BytesPerLine */
  1, /* BitsPerPixel */
  acsilence_icon,  /* Pointer to picture data (indices) */
  &Palsilence_icon  /* Pointer to palette */
};

/* *** End of file *** */
