/***************************************************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: Standby_Icon
* Dimensions:  187 * 48
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsStandby_Icon[] = {
     0xFFFFFF,0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalStandby_Icon = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsStandby_Icon[0]
};

static GUI_CONST_STORAGE unsigned char acStandby_Icon[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XXXXXXXX, X_______, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XXXXXX__, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XXXX____, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XXX_____, ________, _____XXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XXX_____, ________, _____XXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XX______, ________, _____XXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XX______, __XXXXXX, _____XXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  X_______, _XXXXXXX, XXX__XXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  X_______, XXXXXXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  X_______, XXXXXXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXXXXX, XXXX____, _____XXX, XXXXXXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXX__, _____XXX, X_______, XXXXXX__, _____XXX, XX______, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  X_______, XXXXXXXX, XXXXXXXX, X_______, ________, __XXXXXX, ________, _______X, XXXXXXXX, XX______, XXXX____, ______XX, XXXXXXXX, XXXX____, _______X, X_______, XXXXXX__, _____XXX, ________, __XXXXXX, X_______, XXXXXXXX, XXXX____, __X_____,
  X_______, _XXXXXXX, XXXXXXXX, X_______, ________, __XXXXX_, ________, ________, _XXXXXXX, XX______, XX______, _______X, XXXXXXXX, XXX_____, ________, X_______, XXXXXX__, _____X__, ________, ___XXXXX, X_______, XXXXXXXX, XXX_____, ________,
  X_______, __XXXXXX, XXXXXXXX, X_______, ________, __XXXX__, ________, ________, __XXXXXX, XX______, X_______, _______X, XXXXXXXX, XX______, ________, ________, XXXXXX__, ________, ________, ____XXXX, X_______, _XXXXXXX, XXX_____, __X_____,
  X_______, ___XXXXX, XXXXXXXX, X_______, ________, __XXXX__, ________, ________, __XXXXXX, XX______, ________, ________, XXXXXXXX, X_______, ________, ________, XXXXXX__, ________, ________, _____XXX, XX______, _XXXXXXX, XXX_____, __X_____,
  XX______, _____XXX, XXXXXXXX, X_______, ________, __XXXX__, ________, ________, __XXXXXX, XX______, ________, ________, XXXXXXXX, X_______, ________, ________, XXXXXX__, ________, ________, _____XXX, XX______, __XXXXXX, XXX_____, __X_____,
  XX______, _______X, XXXXXXXX, X_______, ________, __XXXX__, ____XXXX, XX______, ___XXXXX, XX______, ____XXXX, ________, _XXXXXXX, ________, _XXXX___, ________, XXXXXX__, ________, _XXXX___, ______XX, XXX_____, __XXXXXX, XX______, _XX_____,
  XXX_____, ________, _XXXXXXX, XXXXX___, ____XXXX, XXXXXX__, _XXXXXXX, XXX_____, ___XXXXX, XX______, ___XXXXX, X_______, _XXXXXXX, ________, XXXXXXX_, ________, XXXXXX__, _______X, XXXXXX__, ______XX, XXX_____, __XXXXXX, XX______, _XX_____,
  XXXX____, ________, ___XXXXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XX______, __XXXXXX, XX______, _XXXXXXX, _______X, XXXXXXXX, ________, XXXXXX__, ______XX, XXXXXXX_, ______XX, XXX_____, ___XXXXX, XX______, _XX_____,
  XXXXX___, ________, ____XXXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXX_, _______X, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXX_, _______X, XXXX____, ___XXXXX, X_______, XXX_____,
  XXXXXXX_, ________, _____XXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXX_, ______XX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, _______X, XXXX____, ___XXXXX, X_______, XXX_____,
  XXXXXXXX, X_______, ______XX, XXXXX___, ____XXXX, XXXXXXXX, XXXX____, ________, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXX_, ______XX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, _______X, XXXX____, ____XXXX, X_______, XXX_____,
  XXXXXXXX, XXX_____, ______XX, XXXXX___, ____XXXX, XXXXXXXX, X_______, ________, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXX_, ______XX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, _______X, XXXXX___, ____XXXX, _______X, XXX_____,
  XXXXXXXX, XXXXX___, _______X, XXXXX___, ____XXXX, XXXXXXXX, ________, ________, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXX_, ______XX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, _______X, XXXXX___, ____XXXX, _______X, XXX_____,
  XXXXXXXX, XXXXXX__, _______X, XXXXX___, ____XXXX, XXXXXXX_, ________, ________, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXX_, ______XX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, _______X, XXXXXX__, _____XXX, _______X, XXX_____,
  XXXXXXXX, XXXXXXX_, _______X, XXXXX___, ____XXXX, XXXXXX__, ________, ________, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXX_, ______XX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, _______X, XXXXXX__, _____XX_, ______XX, XXX_____,
  XXXXXXXX, XXXXXXXX, _______X, XXXXX___, ____XXXX, XXXXXX__, ______XX, XXXX____, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXX_, ______XX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, _______X, XXXXXX__, ______X_, ______XX, XXX_____,
  XXXXXXXX, XXXXXXXX, _______X, XXXXX___, ____XXXX, XXXXX___, _____XXX, XXXX____, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXX_, ______XX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, _______X, XXXXXXX_, ______X_, ______XX, XXX_____,
  XXXXXXXX, XXXXXXXX, _______X, XXXXX___, ____XXXX, XXXXX___, ____XXXX, XXXX____, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXX_, _______X, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXX_, _______X, XXXXXXX_, ______X_, _____XXX, XXX_____,
  __XXXXXX, XXXXXXXX, _______X, XXXXX___, ____XXXX, XXXXX___, ____XXXX, XXXX____, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXXX, _______X, XXXXXXXX, ________, XXXXXX__, ______XX, XXXXXXX_, ______XX, XXXXXXXX, ________, _____XXX, XXX_____,
  ____XXXX, XXXXXXX_, ______XX, XXXXX___, ____XXXX, XXXXX___, ____XXXX, XXXX____, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXXX, ________, XXXXXXX_, ________, XXXXXX__, _______X, XXXXXX__, ______XX, XXXXXXXX, ________, _____XXX, XXX_____,
  _______X, XXXXX___, ______XX, XXXXX___, _____XXX, X_XXX___, ____XXXX, XXX_____, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXXX, ________, _XXXX___, ________, XXXXXX__, ________, _XXXX___, ______XX, XXXXXXXX, ________, ____XXXX, XXX_____,
  ________, ________, _____XXX, XXXXX___, ________, __XXX___, _____XXX, X_______, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXXX, X_______, ________, ________, XXXXXX__, ________, ________, _____XXX, XXXXXXXX, X_______, ____XXXX, XXX_____,
  ________, ________, _____XXX, XXXXXX__, ________, __XXXX__, ________, ________, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXXX, X_______, ________, ________, XXXXXX__, ________, ________, _____XXX, XXXXXXXX, X_______, ____XXXX, XXX_____,
  ________, ________, ____XXXX, XXXXXX__, ________, __XXXX__, ________, ________, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXXX, XX______, ________, _X______, XXXXXX__, ____X___, ________, ____XXXX, XXXXXXXX, X_______, ___XXXXX, XXX_____,
  X_______, ________, ___XXXXX, XXXXXXX_, ________, __XXXXX_, ________, ____X___, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXXX, XXX_____, ________, XX______, XXXXXX__, ____XX__, ________, ___XXXXX, XXXXXXXX, XX______, ___XXXXX, XXX_____,
  XXX_____, ________, _XXXXXXX, XXXXXXXX, ________, __XXXXXX, ________, __XXX___, ___XXXXX, XX______, _XXXXXXX, XX______, _XXXXXXX, XXXX____, _______X, XX______, XXXXXX__, ____XXX_, ________, __XXXXXX, XXXXXXXX, XX______, __XXXXXX, XXX_____,
  XXXXXX__, ______XX, XXXXXXXX, XXXXXXXX, X_______, XXXXXXXX, XX______, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXXXX, XXXXXXXX, XXX_____, __XXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, __XXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, _XXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, _XXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, _XXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _______X, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _______X, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXXXX, XXX_____
};

GUI_CONST_STORAGE GUI_BITMAP bmStandby_Icon = {
  187, /* XSize */
  48, /* YSize */
  24, /* BytesPerLine */
  1, /* BitsPerPixel */
  acStandby_Icon,  /* Pointer to picture data (indices) */
  &PalStandby_Icon  /* Pointer to palette */
};

/* *** End of file *** */
