/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: X45A
* Dimensions:  165 * 30
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsX45A[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalX45A = {
  2,	/* number of entries */
  1, 	/* No transparency */
  &ColorsX45A[0]
};

static GUI_CONST_STORAGE unsigned char acX45A[] = {
	XXXXXXXX, XXXX____, _______X, XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
		_XXXXXXX, XXXXX___, ______XX, XXXXXXXX, X___XXXX, XXXXX___, ________, ________, _XXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
		__XXXXXX, XXXXXX__, _____XXX, XXXXXXXX, X___XXXX, XXXXX___, ________, ________, _XXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
		___XXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, ____XXXX, XXXXX___, ________, ________, _XXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
		____XXXX, XXXXXXXX, ___XXXXX, XXXXXXX_, ____XXXX, XXXXX___, ________, ________, _XXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
		_____XXX, XXXXXXXX, X_XXXXXX, XXXXXX__, ____XXXX, XXXXX___, ________, ________, _XXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
		______XX, XXXXXXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXX___, ________, ________, _XXXXXXX, X_____XX, XXXXXXXX, ________, ________, ________, ________, ______XX, XXXXXXXX, X_______, ________, ____XXXX, XXXXXXX_,
		_______X, XXXXXXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXX___, ________, ________, _XXXXXXX, X_____XX, XXXXXXXX, ________, ________, ________, ________, ______XX, XXXXXXXX, ________, ________, _____XXX, XXXXXXX_,
		_______X, XXXXXXXX, XXXXXXXX, XXXX____, ____XXXX, XXXXXX__, ________, ________, XXXXXXXX, X_____XX, XXXXXXX_, ________, ________, ________, ________, ______XX, XXXXXXXX, ________, ________, _____XXX, XXXXXXX_,
		________, XXXXXXXX, XXXXXXXX, XXX_____, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, ________, ________, ________, ________, ______XX, XXXXXXXX, ________, ________, _____XXX, XXXXXXX_,
		________, _XXXXXXX, XXXXXXXX, XX______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, ________, ________, _____XXX, XXXXXXX_,
		________, __XXXXXX, XXXXXXXX, XX______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ______XX, XXXXXXXX, ________, ________, _____XXX, XXXXXXX_,
		________, ___XXXXX, XXXXXXXX, X_______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
		________, ____XXXX, XXXXXXXX, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
		________, ____XXXX, XXXXXXXX, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
		________, _____XXX, XXXXXXXX, X_______, ________, ________, ________, ________, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
		________, ______XX, XXXXXXXX, XX______, ________, ________, ________, ________, _XXXXXXX, X_______, ________, ________, ________, _____XXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
		________, _XX____X, XXXXXXXX, XX______, ________, ________, ________, ________, _XXXXXXX, X_______, ________, ________, ________, ______XX, XXXXXXX_, ______XX, XXXXXXX_, ________, ________, ______XX, XXXXXXX_,
		________, XXXX____, XXXXXXXX, XXX_____, ________, ________, ________, ________, _XXXXXXX, X_______, ________, ________, ________, ______XX, XXXXXXX_, ______XX, XXXXXXX_, ________, ________, ______XX, XXXXXXX_,
		________, XXXXX___, _XXXXXXX, XXXX____, ________, ________, ________, ________, _XXXXXXX, X_______, ________, ________, ________, _____XXX, XXXXXXX_, ______XX, XXXXXXX_, ________, ________, ______XX, XXXXXXX_,
		_______X, XXXXXX__, __XXXXXX, XXXXX___, ________, ________, ________, ________, _XXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXX_, ________, ________, ______XX, XXXXXXX_,
		______XX, XXXXXXX_, ___XXXXX, XXXXXX__, ________, ________, ________, ________, _XXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXX_, ________, ________, ______XX, XXXXXXX_,
		_____XXX, XXXXXXXX, ____XXXX, XXXXXXX_, ________, ________, ________, ________, _XXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXX_, ________, ________, ______XX, XXXXXXX_,
		____XXXX, XXXXXXXX, ____XXXX, XXXXXXX_, ________, ________, ________, ________, _XXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXX_, ________, ________, ______XX, XXXXXXX_,
		____XXXX, XXXXXXXX, _____XXX, XXXXXXXX, ________, ________, ________, ________, _XXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ______XX, XXXXXX__, ________, ________, _______X, XXXXXXX_,
		___XXXXX, XXXXXXX_, ______XX, XXXXXXXX, X_______, ________, ________, ________, _XXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXX___, ________, ________, ________, XXXXXXX_,
		__XXXXXX, XXXXXX__, _______X, XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
		_XXXXXXX, XXXXX___, ________, XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
		________, ________, ________, _XXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
		________, ________, ________, __XXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmX45A = {
	167, /* XSize */
	30, /* YSize */
	21, /* BytesPerLine */
	1, /* BitsPerPixel */
	acX45A,  /* Pointer to picture data (indices) */
	&PalX45A  /* Pointer to palette */
};

/* *** End of file *** */
