/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: X6
* Dimensions:  77 * 30
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsX6_GA[] = {
     0xF7F7F7,0x7F3000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalX6_GA = {
  2,	/* number of entries */
  0, 	/* Has transparency */
  &ColorsX6_GA[0]
};

static GUI_CONST_STORAGE GUI_COLOR ColorsX6[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalX6 = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &ColorsX6[0]
};

static GUI_CONST_STORAGE unsigned char acX6[] = {
  XXXXXXXX, XXXX____, _______X, XXXXXXXX, XX______, ________, ________, ________, ________, ________,
  _XXXXXXX, XXXXX___, ______XX, XXXXXXXX, X____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  __XXXXXX, XXXXXX__, _____XXX, XXXXXXXX, X___XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ___XXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ____XXXX, XXXXXXXX, ___XXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  _____XXX, XXXXXXXX, X_XXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  _______X, XXXXXXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXXX__, ________, ________, ________, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXX____, ____XXXX, XXXXX___, ________, ________, ________, ________,
  ________, XXXXXXXX, XXXXXXXX, XXX_____, ____XXXX, XXXXXX__, ________, ________, ________, ________,
  ________, _XXXXXXX, XXXXXXXX, XX______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  ________, __XXXXXX, XXXXXXXX, XX______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  ________, ___XXXXX, XXXXXXXX, X_______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ________, ____XXXX, XXXXXXXX, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ________, ____XXXX, XXXXXXXX, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ________, _____XXX, XXXXXXXX, X_______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ________, ______XX, XXXXXXXX, XX______, ____XXXX, XXXXXX__, ________, ________, ___XXXXX, XXXXX___,
  ________, _XX____X, XXXXXXXX, XX______, ____XXXX, XXXXX___, ________, ________, ____XXXX, XXXXX___,
  ________, XXXX____, XXXXXXXX, XXX_____, ____XXXX, XXXXX___, ________, ________, ____XXXX, XXXXX___,
  ________, XXXXX___, _XXXXXXX, XXXX____, ____XXXX, XXXXXX__, ________, ________, ___XXXXX, XXXXX___,
  _______X, XXXXXX__, __XXXXXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ______XX, XXXXXXX_, ___XXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  _____XXX, XXXXXXXX, ____XXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ____XXXX, XXXXXXXX, ____XXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ____XXXX, XXXXXXXX, _____XXX, XXXXXXXX, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  ___XXXXX, XXXXXXX_, ______XX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  __XXXXXX, XXXXXX__, _______X, XXXXXXXX, XX______, ________, ________, ________, ________, ________,
  _XXXXXXX, XXXXX___, ________, XXXXXXXX, XXX_____, ________, ________, ________, ________, ________,
  ________, ________, ________, _XXXXXXX, XXXX____, ________, ________, ________, ________, ________,
  ________, ________, ________, __XXXXXX, XXXXX___, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmX6 = {
  77, /* XSize */
  30, /* YSize */
  10, /* BytesPerLine */
  1, /* BitsPerPixel */
  acX6,  /* Pointer to picture data (indices) */
  &PalX6  /* Pointer to palette */
};

GUI_CONST_STORAGE GUI_BITMAP bmX6_GA = {
  77, /* XSize */
  30, /* YSize */
  10, /* BytesPerLine */
  1, /* BitsPerPixel */
  acX6,  /* Pointer to picture data (indices) */
  &PalX6_GA  /* Pointer to palette */
};

/* *** End of file *** */
